=== adele-robots/fiona/FIOPRE/WebContent/WEB-INF/formatter/fwnScheme.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

<xs:element name="formatter">
  <xs:complexType>
	<xs:choice maxOccurs="unbounded">
		<xs:element name="destino" type="fieldType"></xs:element>
		<xs:element name="componenteIterativo">
			<xs:complexType>
				<xs:sequence maxOccurs="unbounded">
					<xs:element name="destino" type="fieldTypeLista" />
				</xs:sequence>
				<xs:attribute name="nombre" use="required"
					type="xs:string" />
				<xs:attribute name="persist" use="optional"
					type="xs:string" />
				<xs:attribute name="sesion" use="optional"
					type="xs:string" />
			</xs:complexType>
		</xs:element>
		<xs:element name="contexto" type="contextoType"></xs:element>
	</xs:choice>
  </xs:complexType>
</xs:element>



<xs:simpleType name="datoType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="String"/>
    <xs:enumeration value="BigDecimal"/>
	<xs:enumeration value="Producto"/>
    <xs:enumeration value="Registro"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="datoTypeSN">
  <xs:restriction base="xs:string">
    <xs:enumeration value="String"/>
    <xs:enumeration value="BigDecimal"/>
    <xs:enumeration value="Date"/>
	<xs:enumeration value="Producto"/>
	<xs:enumeration value="Contexto"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="datoTypeCtx">
  <xs:restriction base="xs:string">
    <xs:enumeration value="String"/>
    <xs:enumeration value="BigDecimal"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="funciones">
  <xs:restriction base="xs:string">
    <xs:enumeration value="FuncionConcatenar"/>
    <xs:enumeration value="FuncionComparar"/>
    <xs:enumeration value="FuncionSuma"/>
    <xs:enumeration value="FuncionResta"/>
    <xs:enumeration value="FuncionMultiplica"/>
    <xs:enumeration value="FuncionDivide"/>
    <xs:enumeration value="FuncionSubString"/>
    <xs:enumeration value="FuncionMayusculas"/>
    <xs:enumeration value="FuncionMinusculas"/>
    <xs:enumeration value="FuncionCompletar"/>
    <xs:enumeration value="FuncionConstante"/>
    <xs:enumeration value="FuncionCuenta"/>
  </xs:restriction>
</xs:simpleType>


<xs:complexType name="fieldType">
	 <xs:choice>
	            <xs:element name="origen">
	            	<xs:complexType>
	            		<xs:sequence>
	            			<xs:element name="registro"
	            				type="registroType" maxOccurs="1" minOccurs="0">
	            			</xs:element>
	            			<xs:element name="registroIterativo"
	            				type="registroIterativoType" maxOccurs="1" minOccurs="0">
	            			</xs:element>
	            		</xs:sequence>
	            		<xs:attribute name="nombre" use="required"
	            			type="xs:string">
	            		</xs:attribute>
	            		<xs:attribute name="tipoDatoValor"
	            			use="optional" type="datoType">
	            		</xs:attribute>
	            		<xs:attribute name="propiedadValor"
	            			use="optional" type="xs:string">
	            		</xs:attribute>
	            	</xs:complexType>
	            </xs:element>
	            <xs:element name="funcion">
           	        	 <xs:complexType>
           	        	      <xs:sequence>
			            		  <xs:element name="origen" maxOccurs="unbounded">
					            	<xs:complexType>
					            		<xs:attribute name="nombre" use="required" type="xs:string"/>
					            	    <xs:attribute name="tipoDatoValor" use="optional" type="datoType"> </xs:attribute>
	            						<xs:attribute name="propiedadValor" use="optional" type="xs:string"> </xs:attribute>
					            	</xs:complexType>
	           					  </xs:element>
           					  </xs:sequence>
           	        	    <xs:attribute name="method" use="required" type="funciones"/>
           	       		 </xs:complexType>
           	    </xs:element>
	</xs:choice>
  <xs:attribute name="nombre" use="optional" type="xs:string"/>
  <xs:attribute name="tipoDato" use="optional" type="datoTypeSN" />
  <xs:attribute name="persist" use="optional" type="xs:string" />
   <xs:attribute name="sesion" use="optional" type="xs:string" />
</xs:complexType>

<xs:complexType name="fieldTypeLista">
	 <xs:sequence>
	            <xs:element name="origen">
	            	<xs:complexType>
	            		<xs:sequence>
	            			<xs:element name="registro"
	            				type="registroType" maxOccurs="1" minOccurs="0">
	            			</xs:element>
	            			<xs:element name="registroIterativo"
	            				type="registroIterativoType" maxOccurs="1" minOccurs="0">
	            			</xs:element>
	            		</xs:sequence>
	            		<xs:attribute name="nombre" use="required"
	            			type="xs:string">
	            		</xs:attribute>
	            		<xs:attribute name="tipoDatoValor"
	            			use="required" type="datoType">
	            		</xs:attribute>
	            		<xs:attribute name="propiedadValor"
	            			use="required" type="xs:string">
	            		</xs:attribute>
	            		<xs:attribute name="tipoDatoEtiqueta"
	            			type="datoType">
	            		</xs:attribute>
	            		<xs:attribute name="propiedadEtiqueta"
	            			type="xs:string">
	            		</xs:attribute>
	            	</xs:complexType>
	            </xs:element>
	</xs:sequence>
  <xs:attribute name="nombre" use="required" type="xs:string"/>
</xs:complexType>


    <xs:complexType name="registroType">
    	<xs:attribute name="propiedadValor" type="xs:string"></xs:attribute>
    	<xs:attribute name="tipoDatoValor" type="datoTypeCtx"></xs:attribute>
    	<xs:attribute name="nombre" type="xs:string"></xs:attribute>
    	<xs:attribute name="tipoDatoEtiqueta" type="datoTypeCtx"></xs:attribute>
    	<xs:attribute name="propiedadEtiqueta" type="xs:string"></xs:attribute>
    </xs:complexType>


    <xs:complexType name="registroIterativoType">
    	<xs:sequence>
    		<xs:element name="registro" type="registroType" maxOccurs="unbounded" minOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="contextoType">
    	<xs:sequence>
    		<xs:element name="destino" type="destinoCtxType" maxOccurs="unbounded" minOccurs="0"></xs:element>
    		<xs:element name="registro" type="registroEntrType" maxOccurs="unbounded" minOccurs="0"></xs:element>
    		<xs:element name="registroIterativo" type="registroIterativoEntrType" maxOccurs="unbounded" minOccurs="0"></xs:element>
    	</xs:sequence>
    	<xs:attribute name="refCtx" type="xs:string"></xs:attribute>
    	<xs:attribute name="nombreCtx" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="registroEntrType">
    	<xs:sequence>
    		<xs:element name="destino" type="destinoCtxType" maxOccurs="unbounded" minOccurs="0"></xs:element>
    		<xs:element name="registro" type="registroEntrType" maxOccurs="unbounded" minOccurs="0"></xs:element>
    		<xs:element name="registroIterativo" type="registroIterativoEntrType" maxOccurs="unbounded" minOccurs="0"></xs:element>
    	</xs:sequence>
    	<xs:attribute name="nombreReg" type="xs:string"></xs:attribute>
    </xs:complexType>
    
    <xs:complexType name="registroIterativoEntrType">
    	<xs:sequence>
    		<xs:element name="registro" type="registroEntrType"
    			maxOccurs="unbounded" minOccurs="0">
    		</xs:element>
    	</xs:sequence>
    	<xs:attribute name="nombre" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="destinoCtxType">
    	<xs:sequence>
    		<xs:element name="origen" type="OrigenCtxType" maxOccurs="1" minOccurs="1"></xs:element>
    	</xs:sequence>
    	<xs:attribute name="propiedadValor" type="xs:string"></xs:attribute>
    	<xs:attribute name="tipoDatoValor" type="datoTypeCtx"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="tipoDatoValorCtxType"></xs:complexType>

    <xs:complexType name="OrigenCtxType">
    	<xs:attribute name="nombre" type="xs:string"></xs:attribute>
    </xs:complexType>
</xs:schema>

=== adele-robots/fiona/FIOPRE/WebContent/WEB-INF/formatter/sendInvitations/SendInvitations_VO_029_021.xml
<?xml version="1.0" encoding="UTF-8"?>
<formatter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../fwnScheme.xsd">  
  
  <destino nombre="00" tipoDato="String">
    <origen nombre="nombre" />
  </destino>
  <destino nombre="01" tipoDato="String">
    <origen nombre="apellido" />
  </destino>
  <destino nombre="02" tipoDato="String">
    <origen nombre="emailInvitado" />
  </destino>
   <destino nombre="03" tipoDato="String">
    <origen nombre="SECURE_USERID" />
  </destino>
  <destino nombre="04" tipoDato="String">
    <origen nombre="emailBody" />
  </destino>
  
  
  
</formatter>

=== adele-robots/fiona/FIOPRE/WebContent/WEB-INF/formatter/sparkStore/FIOPRE_ListAllSparks_OV_029_015.xml
<?xml version="1.0" encoding="UTF-8"?>

<formatter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../fwnScheme.xsd">  

	<componenteIterativo nombre="sparksTabla"
		persist="lstSparks">

		<destino nombre="spark_id">
			<origen nombre="FIONEGN004" tipoDatoValor="BigDecimal"
				propiedadValor="FIONEG004010" />
		</destino>

		<destino nombre="nombre">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004020" />
		</destino>

		<destino nombre="descripcion">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004040" />
		</destino>
		
		<destino nombre="comprado">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004190" />
		</destino>
	<!-- 
		<destino nombre="precio">
			<origen nombre="FIONEGN004" tipoDatoValor="BigDecimal"
				propiedadValor="FIONEG004040" />
		</destino>  -->		
		
		<destino nombre="iconPath">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004230" />
		</destino>

	</componenteIterativo>

	
</formatter>

=== adele-robots/fiona/FIOPRE/WebContent/WEB-INF/formatter/myprofile/MyProfile_SaveSes_VO_029_002.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<formatter 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:noNamespaceSchemaLocation="../fwnScheme.xsd">

	<destino nombre="00" tipoDato="BigDecimal">
		<!-- El identificador del usuario conectado almacenado en session -->
		<origen nombre="SECURE_USERID" />
	</destino>
	<destino nombre="01" tipoDato="String">
		<origen nombre="SES_USER_FISTNAME" />
	</destino>
	<destino nombre="02" tipoDato="String">
		<origen nombre="SES_USER_SURNAME" />
	</destino>
	<destino nombre="03" tipoDato="String">
		<!-- @TODO: Cambiar cuando se active el AvatarBuilder encoded userpath 
			en negocio para permitir al usuario cambiar su email. 
			Ahora no se puede porque este campo se calcula a partir del email y si se deja cambiar
			se pierden todos las configuraciones del avatar para el usuario
		<origen nombre="USER_MAIL" />
		-->
		<origen nombre="SECURE_USERMAIL" />
	</destino>
	<destino nombre="04" tipoDato="String">
		<origen nombre="SES_USER_NEWPASSWORD1" />
	</destino>
	<destino nombre="05" tipoDato="String">
		<!-- El propio usuario no puede cambiar su status asi que lo cogemos de session -->
		<origen nombre="SECURE_USER_STATUS" />
	</destino>
	<destino nombre="06" tipoDato="BigDecimal">
		<!-- @TODO: Este campo esta disabled en la view asi que lo cogemos de session
		<origen nombre="USER_ENTITY_ID" /> -->
		<origen nombre="SECURE_USER_ENTITY_ID" />
	</destino>
	<destino nombre="07" tipoDato="BigDecimal">
		<origen nombre="SES_USER_ACCOUNTTYPE_ID" />
	</destino>
	<destino nombre="08" tipoDato="BigDecimal">
		<!-- @TODO: Este campo esta disabled en la view asi que lo cogemos de session
		<origen nombre="USER_CREDITCARD_NUMBER" /> -->
		<origen nombre="SECURE_USER_CREDITCARD_NUMBER" />
	</destino>
	<destino nombre="09" tipoDato="String">
		<!-- @TODO: Este campo esta disabled en la view asi que lo cogemos de session
		<origen nombre="USER_CREDITCARD_EXPIRATION" /> -->
		<origen nombre="SECURE_USER_CREDITCARD_EXPIRATION" />
	</destino>
	<destino nombre="10" tipoDato="String">
		<!-- El propio usuario no puede cambiar su codigo de confirmacion de registro asi que lo cogemos de session -->
		<origen nombre="SECURE_USER_SIGNUPCODE" />
	</destino>
	<destino nombre="11" tipoDato="String">
		<origen nombre="SES_USER_NICKNAME" />
	</destino>
	<destino nombre="12" tipoDato="BigDecimal">
		<!-- El propio usuario no puede cambiar su rol asi que lo cogemos de session -->
		<origen nombre="SECURE_USER_USERGROUP_ID" />
	</destino>
	<destino nombre="13" tipoDato="String">
		<origen nombre="SES_USER_TITLE" />
	</destino>
	<destino nombre="14" tipoDato="String">
		<origen nombre="SES_USER_FLAGENTITY" />
	</destino>
	<destino nombre="15" tipoDato="BigDecimal">
		<origen nombre="SES_USER_ORGANIZATIONTYPE_ID" />
	</destino>
	<destino nombre="16" tipoDato="String">
		<origen nombre="SES_USER_LEGALENTITYNAME" />
	</destino>
	<destino nombre="17" tipoDato="String">
		<origen nombre="SES_USER_WEBSITE" />
	</destino>
	<destino nombre="18" tipoDato="String">
		<origen nombre="SES_USER_WORKEMAIL" />
	</destino>
	<destino nombre="19" tipoDato="String">
		<origen nombre="SES_USER_COUNTRYCODE" />
	</destino>
	<destino nombre="20" tipoDato="String">
		<origen nombre="SES_USER_PHONENUMBER" />
	</destino>
	<destino nombre="21" tipoDato="String">
		<origen nombre="SES_USER_EXT" />
	</destino>
	<destino nombre="22" tipoDato="String">
		<origen nombre="SES_USER_ACCOUNTTYPE_METHOD" />
	</destino>

</formatter>

=== adele-robots/fiona/FIOPRE/WebContent/WEB-INF/formatter/signup/Signup_Save_VV_029_001.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<formatter 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:noNamespaceSchemaLocation="../fwnScheme.xsd">

	<destino persist="USER_FISTNAME">
		<origen nombre="USER_FISTNAME" />
	</destino>
	<destino persist="USER_SURNAME">
		<origen nombre="USER_SURNAME" />
	</destino>
	<destino persist="USER_MAIL">
		<origen nombre="USER_MAIL" />
	</destino>
	<destino persist="USER_PASSWORD1">
		<origen nombre="USER_PASSWORD1" />
	</destino>
	<destino persist="USER_ENTITY_ID">
		<origen nombre="USER_ENTITY_ID" />
	</destino>
	<destino persist="USER_ACCOUNTTYPE_ID">
		<origen nombre="USER_ACCOUNTTYPE_ID" />
	</destino>
	<destino persist="USER_CREDITCARD_NUMBER">
		<origen nombre="USER_CREDITCARD_NUMBER" />
	</destino>
	<destino persist="USER_CREDITCARD_EXPIRATION">
		<origen nombre="USER_CREDITCARD_EXPIRATION" />
	</destino>
	<destino persist="USER_NICKNAME">
		<origen nombre="USER_NICKNAME" />
	</destino>	
	<destino persist="USER_TITLE">
		<origen nombre="USER_TITLE" />
	</destino>
	<destino persist="USER_FLAGENTITY">
		<origen nombre="USER_FLAGENTITY" />
	</destino>
	<destino persist="USER_ORGANIZATIONTYPE_ID">
		<origen nombre="USER_ORGANIZATIONTYPE_ID" />
	</destino>
	<destino persist="USER_LEGALENTITYNAME">
		<origen nombre="USER_LEGALENTITYNAME" />
	</destino>
	<destino persist="USER_WEBSITE">
		<origen nombre="USER_WEBSITE" />
	</destino>
	<destino persist="USER_WORKEMAIL">
		<origen nombre="USER_WORKEMAIL" />
	</destino>
	<destino persist="USER_COUNTRYCODE">
		<origen nombre="USER_COUNTRYCODE" />
	</destino>
	<destino persist="USER_PHONENUMBER">
		<origen nombre="USER_PHONENUMBER" />
	</destino>
	<destino persist="USER_EXT">
		<origen nombre="USER_EXT" />
	</destino>
	<destino persist="USER_ACCOUNTTYPE_METHOD">
		<origen nombre="USER_ACCOUNTTYPE_METHOD" />
	</destino>

</formatter>

=== adele-robots/fiona/FIOPRE/WebContent/WEB-INF/formatter/signup/Signup_Save_VO_029_065.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<formatter 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:noNamespaceSchemaLocation="../fwnScheme.xsd">

	<destino nombre="00" tipoDato="BigDecimal">
		<origen nombre="USER_ID" />
	</destino>
	<!-- El identificador del tipo de cuenta FREE es 1 -->
	<destino nombre="01" tipoDato="BigDecimal">
		<funcion method="FuncionConstante">
			<origen nombre="1" />
		</funcion>
	</destino>
	<!-- El flag para resetear el crédito -->
	<destino nombre="01" tipoDato="BigDecimal">
		<funcion method="FuncionConstante">
			<origen nombre="1" />
		</funcion>
	</destino>
	

</formatter>

=== adele-robots/fiona/FIOPRE/WebContent/WEB-INF/formatter/sparkStore/FIOPRE_SparkInformation_OV_029_016.xml
<?xml version="1.0" encoding="UTF-8"?>

<formatter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../fwnScheme.xsd">  

		<destino nombre="spark_id">
			<origen nombre="FIONEGN004" tipoDatoValor="BigDecimal"
				propiedadValor="FIONEG004010" />
		</destino>

		<destino nombre="nombre">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004020" />
		</destino>

		<destino nombre="descripcion">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004040" />
		</destino>
		
		<destino nombre="version">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004050" />
		</destino>
		
		<destino nombre="descCorta">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004060" />
		</destino>
		
		<destino nombre="novedades">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004070" />
		</destino>
		
		<destino nombre="otrosKeywords">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004080" />
		</destino>
		
		<destino nombre="email">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004090" />
		</destino>
		
		<destino nombre="marketingURL">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004100" />
		</destino>		
		
		<destino nombre="esTrial">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004140" />
		</destino>
		
		<destino nombre="diasTrial">
			<origen nombre="FIONEGN004" tipoDatoValor="BigDecimal"
				propiedadValor="FIONEG004150" />
		</destino>
		
		<destino nombre="icono">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004160" />
		</destino>
				
		<destino nombre="banner">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004170" />
		</destino>
		
		<destino nombre="video">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004180" />
		</destino>	
		
		<destino nombre="comprado">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004190" />
		</destino>
		
		<destino nombre="status_id">
			<origen nombre="FIONEGN004" tipoDatoValor="BigDecimal"
				propiedadValor="FIONEG004200" />
		</destino>
		
		<destino nombre="status">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004210" />
		</destino>
		
		<destino nombre="borrado">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004220" />
		</destino>
		
		<destino nombre="iconPath">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004230" />
		</destino>	
		
		
		<destino nombre="valoracion">
			<funcion method="FuncionConstante">
		    	<origen nombre="0"></origen>
		    </funcion>
		</destino>
		
		<!-- Usado únicamente para identificar el tipo
		de tarifa elegida por el usuario en presentación  -->
		<destino nombre="idTarifa">			
				<origen nombre="FIONEGN004" tipoDatoValor="BigDecimal"
				propiedadValor="FIONEG004290" />		
			
		</destino>
		
		<destino nombre="idTarifaProd">			
				<origen nombre="FIONEGN004" tipoDatoValor="BigDecimal"
				propiedadValor="FIONEG004300" />		
			
		</destino>
		
		<!-- Campos pertenecientes al precio de un spark comprado
		por un usuario -->
		<destino nombre="precio_usuarios">
			<origen nombre="FIONEGN004" tipoDatoValor="BigDecimal"
				propiedadValor="FIONEG004120"/>
		</destino>
		
		<destino nombre="precio_unidad">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004130"/>
		</destino> 
		
		<destino nombre="precio_cantidad">
			<origen nombre="FIONEGN004" tipoDatoValor="BigDecimal"
				propiedadValor="FIONEG004250"/>
		</destino>
		
		<destino nombre="precio_precio">
			<origen nombre="FIONEGN004" tipoDatoValor="BigDecimal"
				propiedadValor="FIONEG004260"/>
		</destino>
		
		<!-- Valoración media del spark -->
		<destino nombre="valoracion_media">
			<origen nombre="FIONEGN004" tipoDatoValor="BigDecimal"
				propiedadValor="FIONEG004310"/>
		</destino>
		
		<!-- Número total de opiniones del spark -->
		<destino nombre="num_opiniones">
			<origen nombre="FIONEGN004" tipoDatoValor="BigDecimal"
				propiedadValor="FIONEG004320"/>
		</destino>
		
		<!-- Nombre del usuario que desarrolló el spark -->
		<destino nombre="nombre_usuario_desarrollador">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004330"/>
		</destino>
		
		<!-- Email de la cuenta Paypal del usuario -->
		<destino nombre="emailPaypal">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004340"/>
		</destino>
		
				
		
		<componenteIterativo nombre="opinionTabla"
		persist="lstOpiniones">

			<destino nombre="opinion_id">
				<origen nombre="FIONEGN006" tipoDatoValor="BigDecimal"
					propiedadValor="FIONEG006010" />
			</destino>
	
			<destino nombre="opinion_rate">
				<origen nombre="FIONEGN006" tipoDatoValor="BigDecimal"
					propiedadValor="FIONEG006020" />
			</destino>
	
			<destino nombre="opinion_descripcion">
				<origen nombre="FIONEGN006" tipoDatoValor="String"
					propiedadValor="FIONEG006030" />
			</destino>
			
			<destino nombre="opinion_titulo">
				<origen nombre="FIONEGN006" tipoDatoValor="String"
					propiedadValor="FIONEG006040" />
			</destino>
			
			<destino nombre="opinion_fecha">
				<origen nombre="FIONEGN006" tipoDatoValor="String"
					propiedadValor="FIONEG006050" />
			</destino>		 
			

		</componenteIterativo>
		
		<componenteIterativo nombre="keywordTabla"
		persist="lstSparkKeywords">				 
			
			<destino nombre="productonoasignado">
				<origen nombre="FIONEGN012" tipoDatoValor="BigDecimal"
					tipoDatoEtiqueta="String" propiedadValor="FIONEG012010"
					propiedadEtiqueta="FIONEG012020" />
			</destino>
			

		</componenteIterativo>
		
		
		<componenteIterativo nombre="precioTabla"
		persist="preciosList">	
		
			<destino nombre="price_id">
				<origen nombre="FIONEGN019" tipoDatoValor="BigDecimal"
					propiedadValor="FIONEG019010" />
			</destino>			 
			
			<destino nombre="num_usuarios">
				<origen nombre="FIONEGN019" tipoDatoValor="BigDecimal"
					propiedadValor="FIONEG019020" />
			</destino>		
			
			<destino nombre="cantidad">
				<origen nombre="FIONEGN019" tipoDatoValor="BigDecimal"
					propiedadValor="FIONEG019050" />
			</destino>
			
			<destino nombre="euros">
				<origen nombre="FIONEGN019" tipoDatoValor="BigDecimal"
					propiedadValor="FIONEG019060" />
			</destino>
			
			<destino nombre="unidad_nombre">
				<origen nombre="FIONEGN019" tipoDatoValor="String"
					propiedadValor="FIONEG019080" />
			</destino>
			
			<destino nombre="es_activo">
				<origen nombre="FIONEGN019" tipoDatoValor="String"
					propiedadValor="FIONEG019090"/>
			</destino>
			
			<destino nombre="es_usado">
				<origen nombre="FIONEGN019" tipoDatoValor="String"
					propiedadValor="FIONEG019100"/>
			</destino>
			

		</componenteIterativo>
		
		<componenteIterativo nombre="precioTabla"
		persist="preciosProdList">	
		
			<destino nombre="price_id">
				<origen nombre="FIONEGN022" tipoDatoValor="BigDecimal"
					propiedadValor="FIONEG022010" />
			</destino>			 
			
			<destino nombre="num_usuarios">
				<origen nombre="FIONEGN022" tipoDatoValor="BigDecimal"
					propiedadValor="FIONEG022020" />
			</destino>		
			
			<destino nombre="cantidad">
				<origen nombre="FIONEGN022" tipoDatoValor="BigDecimal"
					propiedadValor="FIONEG022050" />
			</destino>
			
			<destino nombre="euros">
				<origen nombre="FIONEGN022" tipoDatoValor="BigDecimal"
					propiedadValor="FIONEG022060" />
			</destino>
			
			<destino nombre="unidad_nombre">
				<origen nombre="FIONEGN022" tipoDatoValor="String"
					propiedadValor="FIONEG022080" />
			</destino>
			
			<destino nombre="es_activo">
				<origen nombre="FIONEGN022" tipoDatoValor="String"
					propiedadValor="FIONEG022090"/>
			</destino>
			
			<destino nombre="es_usado">
				<origen nombre="FIONEGN022" tipoDatoValor="String"
					propiedadValor="FIONEG022100"/>
			</destino>
			

		</componenteIterativo>
		
		<componenteIterativo nombre="sparksTabla"
		persist="lstRelatedSparks">

			<destino nombre="spark_id">
				<origen nombre="FIONEGN004" tipoDatoValor="BigDecimal"
					propiedadValor="FIONEG004010" />
			</destino>
	
			<destino nombre="nombre">
				<origen nombre="FIONEGN004" tipoDatoValor="String"
					propiedadValor="FIONEG004020" />
			</destino>
	
			<destino nombre="descripcion">
				<origen nombre="FIONEGN004" tipoDatoValor="String"
					propiedadValor="FIONEG004040" />
			</destino>
			
			<destino nombre="comprado">
				<origen nombre="FIONEGN004" tipoDatoValor="String"
					propiedadValor="FIONEG004190" />
			</destino>
			
			<destino nombre="iconPath">
				<origen nombre="FIONEGN004" tipoDatoValor="String"
					propiedadValor="FIONEG004230" />
			</destino>
			
			<destino nombre="statusDate">
				<origen nombre="FIONEGN004" tipoDatoValor="String"
					propiedadValor="FIONEG004240" />
			</destino>
			
			<!-- Usado únicamente para identificar el tipo
			de tarifa elegida por el usuario en presentación  -->
			<destino nombre="idTarifa">			
					<origen nombre="FIONEGN004" tipoDatoValor="BigDecimal"
					propiedadValor="FIONEG004290" />		
				
			</destino>
	

		</componenteIterativo>

			
</formatter>
