=== adele-robots/fiona/FIOPRE/WebContent/WEB-INF/formatter/fwnScheme.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

<xs:element name="formatter">
  <xs:complexType>
	<xs:choice maxOccurs="unbounded">
		<xs:element name="destino" type="fieldType"></xs:element>
		<xs:element name="componenteIterativo">
			<xs:complexType>
				<xs:sequence maxOccurs="unbounded">
					<xs:element name="destino" type="fieldTypeLista" />
				</xs:sequence>
				<xs:attribute name="nombre" use="required"
					type="xs:string" />
				<xs:attribute name="persist" use="optional"
					type="xs:string" />
				<xs:attribute name="sesion" use="optional"
					type="xs:string" />
			</xs:complexType>
		</xs:element>
		<xs:element name="contexto" type="contextoType"></xs:element>
	</xs:choice>
  </xs:complexType>
</xs:element>



<xs:simpleType name="datoType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="String"/>
    <xs:enumeration value="BigDecimal"/>
	<xs:enumeration value="Producto"/>
    <xs:enumeration value="Registro"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="datoTypeSN">
  <xs:restriction base="xs:string">
    <xs:enumeration value="String"/>
    <xs:enumeration value="BigDecimal"/>
    <xs:enumeration value="Date"/>
	<xs:enumeration value="Producto"/>
	<xs:enumeration value="Contexto"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="datoTypeCtx">
  <xs:restriction base="xs:string">
    <xs:enumeration value="String"/>
    <xs:enumeration value="BigDecimal"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="funciones">
  <xs:restriction base="xs:string">
    <xs:enumeration value="FuncionConcatenar"/>
    <xs:enumeration value="FuncionComparar"/>
    <xs:enumeration value="FuncionSuma"/>
    <xs:enumeration value="FuncionResta"/>
    <xs:enumeration value="FuncionMultiplica"/>
    <xs:enumeration value="FuncionDivide"/>
    <xs:enumeration value="FuncionSubString"/>
    <xs:enumeration value="FuncionMayusculas"/>
    <xs:enumeration value="FuncionMinusculas"/>
    <xs:enumeration value="FuncionCompletar"/>
    <xs:enumeration value="FuncionConstante"/>
    <xs:enumeration value="FuncionCuenta"/>
  </xs:restriction>
</xs:simpleType>


<xs:complexType name="fieldType">
	 <xs:choice>
	            <xs:element name="origen">
	            	<xs:complexType>
	            		<xs:sequence>
	            			<xs:element name="registro"
	            				type="registroType" maxOccurs="1" minOccurs="0">
	            			</xs:element>
	            			<xs:element name="registroIterativo"
	            				type="registroIterativoType" maxOccurs="1" minOccurs="0">
	            			</xs:element>
	            		</xs:sequence>
	            		<xs:attribute name="nombre" use="required"
	            			type="xs:string">
	            		</xs:attribute>
	            		<xs:attribute name="tipoDatoValor"
	            			use="optional" type="datoType">
	            		</xs:attribute>
	            		<xs:attribute name="propiedadValor"
	            			use="optional" type="xs:string">
	            		</xs:attribute>
	            	</xs:complexType>
	            </xs:element>
	            <xs:element name="funcion">
           	        	 <xs:complexType>
           	        	      <xs:sequence>
			            		  <xs:element name="origen" maxOccurs="unbounded">
					            	<xs:complexType>
					            		<xs:attribute name="nombre" use="required" type="xs:string"/>
					            	    <xs:attribute name="tipoDatoValor" use="optional" type="datoType"> </xs:attribute>
	            						<xs:attribute name="propiedadValor" use="optional" type="xs:string"> </xs:attribute>
					            	</xs:complexType>
	           					  </xs:element>
           					  </xs:sequence>
           	        	    <xs:attribute name="method" use="required" type="funciones"/>
           	       		 </xs:complexType>
           	    </xs:element>
	</xs:choice>
  <xs:attribute name="nombre" use="optional" type="xs:string"/>
  <xs:attribute name="tipoDato" use="optional" type="datoTypeSN" />
  <xs:attribute name="persist" use="optional" type="xs:string" />
   <xs:attribute name="sesion" use="optional" type="xs:string" />
</xs:complexType>

<xs:complexType name="fieldTypeLista">
	 <xs:sequence>
	            <xs:element name="origen">
	            	<xs:complexType>
	            		<xs:sequence>
	            			<xs:element name="registro"
	            				type="registroType" maxOccurs="1" minOccurs="0">
	            			</xs:element>
	            			<xs:element name="registroIterativo"
	            				type="registroIterativoType" maxOccurs="1" minOccurs="0">
	            			</xs:element>
	            		</xs:sequence>
	            		<xs:attribute name="nombre" use="required"
	            			type="xs:string">
	            		</xs:attribute>
	            		<xs:attribute name="tipoDatoValor"
	            			use="required" type="datoType">
	            		</xs:attribute>
	            		<xs:attribute name="propiedadValor"
	            			use="required" type="xs:string">
	            		</xs:attribute>
	            		<xs:attribute name="tipoDatoEtiqueta"
	            			type="datoType">
	            		</xs:attribute>
	            		<xs:attribute name="propiedadEtiqueta"
	            			type="xs:string">
	            		</xs:attribute>
	            	</xs:complexType>
	            </xs:element>
	</xs:sequence>
  <xs:attribute name="nombre" use="required" type="xs:string"/>
</xs:complexType>


    <xs:complexType name="registroType">
    	<xs:attribute name="propiedadValor" type="xs:string"></xs:attribute>
    	<xs:attribute name="tipoDatoValor" type="datoTypeCtx"></xs:attribute>
    	<xs:attribute name="nombre" type="xs:string"></xs:attribute>
    	<xs:attribute name="tipoDatoEtiqueta" type="datoTypeCtx"></xs:attribute>
    	<xs:attribute name="propiedadEtiqueta" type="xs:string"></xs:attribute>
    </xs:complexType>


    <xs:complexType name="registroIterativoType">
    	<xs:sequence>
    		<xs:element name="registro" type="registroType" maxOccurs="unbounded" minOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="contextoType">
    	<xs:sequence>
    		<xs:element name="destino" type="destinoCtxType" maxOccurs="unbounded" minOccurs="0"></xs:element>
    		<xs:element name="registro" type="registroEntrType" maxOccurs="unbounded" minOccurs="0"></xs:element>
    		<xs:element name="registroIterativo" type="registroIterativoEntrType" maxOccurs="unbounded" minOccurs="0"></xs:element>
    	</xs:sequence>
    	<xs:attribute name="refCtx" type="xs:string"></xs:attribute>
    	<xs:attribute name="nombreCtx" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="registroEntrType">
    	<xs:sequence>
    		<xs:element name="destino" type="destinoCtxType" maxOccurs="unbounded" minOccurs="0"></xs:element>
    		<xs:element name="registro" type="registroEntrType" maxOccurs="unbounded" minOccurs="0"></xs:element>
    		<xs:element name="registroIterativo" type="registroIterativoEntrType" maxOccurs="unbounded" minOccurs="0"></xs:element>
    	</xs:sequence>
    	<xs:attribute name="nombreReg" type="xs:string"></xs:attribute>
    </xs:complexType>
    
    <xs:complexType name="registroIterativoEntrType">
    	<xs:sequence>
    		<xs:element name="registro" type="registroEntrType"
    			maxOccurs="unbounded" minOccurs="0">
    		</xs:element>
    	</xs:sequence>
    	<xs:attribute name="nombre" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="destinoCtxType">
    	<xs:sequence>
    		<xs:element name="origen" type="OrigenCtxType" maxOccurs="1" minOccurs="1"></xs:element>
    	</xs:sequence>
    	<xs:attribute name="propiedadValor" type="xs:string"></xs:attribute>
    	<xs:attribute name="tipoDatoValor" type="datoTypeCtx"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="tipoDatoValorCtxType"></xs:complexType>

    <xs:complexType name="OrigenCtxType">
    	<xs:attribute name="nombre" type="xs:string"></xs:attribute>
    </xs:complexType>
</xs:schema>

=== adele-robots/fiona/FIOPRE/WebContent/WEB-INF/formatter/sparkStore/FIOPRE_BuySpark_OO_029_020.xml
<?xml version="1.0" encoding="UTF-8"?>
<formatter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../fwnScheme.xsd">

		<destino nombre="0" tipoDato="BigDecimal">
			<origen nombre="FIONEGN004" tipoDatoValor="BigDecimal"
				propiedadValor="FIONEG004010"  />
		</destino>
		
		<destino nombre="01" tipoDato="BigDecimal">
			<origen nombre="SECURE_USERID"/>
		</destino>
				
		<destino persist="sucessBuy" tipoDato="BigDecimal">
			<funcion method="FuncionConstante">
				<origen nombre="true" />
			</funcion>
		</destino>
</formatter>

=== adele-robots/fiona/FIOPRE/WebContent/WEB-INF/formatter/sparkStore/FIOPRE_SaveSpark_OV_029_033.xml
<?xml version="1.0" encoding="UTF-8"?>

<formatter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../fwnScheme.xsd">  

		<destino nombre="spark_id">
			<origen nombre="FIONEGN004" tipoDatoValor="BigDecimal"
				propiedadValor="FIONEG004010" />
		</destino>

		<destino nombre="nombre">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004020" />
		</destino>

		<destino nombre="descripcion">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004040" />
		</destino>
		
		<destino nombre="version">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004050" />
		</destino>
		
		<destino nombre="descCorta">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004060" />
		</destino>
		
		<destino nombre="novedades">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004070" />
		</destino>
		
		<destino nombre="otrosKeywords">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004080" />
		</destino>
		
		<destino nombre="email">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004090" />
		</destino>
		
		<destino nombre="marketingURL">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004100" />
		</destino>
		
		<!-- 
		<destino nombre="numUsuarios">
			<origen nombre="FIONEGN004" tipoDatoValor="BigDecimal"
				propiedadValor="FIONEG004120" />
		</destino>
		
		<destino nombre="idUnidadTiempo">
			<origen nombre="FIONEGN004" tipoDatoValor="BigDecimal"
				propiedadValor="FIONEG004130" />
		</destino> -->
		
		<destino nombre="esTrial">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004140" />
		</destino>
		
		<destino nombre="diasTrial">
			<origen nombre="FIONEGN004" tipoDatoValor="BigDecimal"
				propiedadValor="FIONEG004150" />
		</destino>
		
		<destino nombre="icono">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004160" />
		</destino>
		
		<destino nombre="banner">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004170" />
		</destino>
		
		<destino nombre="video">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004180" />
		</destino>		
		
		<destino nombre="comprado">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004190" />
		</destino>
		
		<destino nombre="status">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004210" />
		</destino>
		
		<destino nombre="unidadValor">
			<origen nombre="FIONEGN004" tipoDatoValor="BigDecimal"
				propiedadValor="FIONEG004250" />
		</destino>
		
		<destino nombre="precio">
			<origen nombre="FIONEGN004" tipoDatoValor="BigDecimal"
				propiedadValor="FIONEG004260" />
		</destino>
		
		<destino nombre="idUnidadUso">
			<origen nombre="FIONEGN004" tipoDatoValor="BigDecimal"
				propiedadValor="FIONEG004270" />
		</destino>
		
		<destino nombre="emailPaypal">
			<origen nombre="FIONEGN004" tipoDatoValor="BigDecimal"
				propiedadValor="FIONEG004340" />
		</destino>

	
</formatter>

=== adele-robots/fiona/FIOPRE/WebContent/WEB-INF/formatter/sparkStore/FIOPRE_ListSparksByCriteria_VO_029_023.xml
<?xml version="1.0" encoding="UTF-8"?>

<formatter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../fwnScheme.xsd">  
  
  <destino nombre="00" tipoDato="BigDecimal">
    <origen nombre="spark_criterio" />
  </destino>
  
   <destino nombre="01" tipoDato="BigDecimal">
    <origen nombre="SECURE_USERID" />
  </destino>
  
  <destino persist="pulsado_top">
    <origen nombre="pulsado_top" />
  </destino>
  
 <destino persist="pulsado_latest">
    <origen nombre="pulsado_latest" />
  </destino>
  
  <destino persist="pulsado_basic">
    <origen nombre="pulsado_basic" />
  </destino>
  
  <destino persist="sucessBuy" tipoDato="BigDecimal">
	<funcion method="FuncionConstante">
		<origen nombre="" />
	</funcion>
  </destino>
  
  <destino persist="errorPaypalSEC" tipoDato="String">
	<funcion method="FuncionConstante">
		<origen nombre="" />
	</funcion>
  </destino>
  
   <destino persist="spark_id" tipoDato="BigDecimal">
	<funcion method="FuncionConstante">
		<origen nombre="" />
	</funcion>
  </destino>
  
  <destino persist="selected_price" tipoDato="BigDecimal">
	<funcion method="FuncionConstante">
		<origen nombre="" />
	</funcion>
  </destino>
  
</formatter>

=== adele-robots/fiona/FIOPRE/WebContent/WEB-INF/formatter/sparkStore/FIOPRE_GetSparkInformation_CBA_VO_029_016.xml
<?xml version="1.0" encoding="UTF-8"?>
<formatter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../fwnScheme.xsd">

		 <destino nombre="00" tipoDato="BigDecimal">
		 	<origen nombre="spark_id" />
		 </destino>

		 <destino nombre="01" tipoDato="BigDecimal">
		 	<origen nombre="SECURE_USERID" />
		 </destino>

		 <destino persist="sucessBuy" tipoDato="BigDecimal">
		 	<funcion method="FuncionConstante">
		 		<origen nombre="" />
		 	</funcion>
		 </destino>
		<!-- 
		 <destino persist="errorPaypalCBA" tipoDato="BigDecimal">
		 	<funcion method="FuncionConstante">
		 		<origen nombre="true" />
		 	</funcion>
		 </destino>  -->
</formatter>

=== adele-robots/fiona/FIOPRE/WebContent/WEB-INF/formatter/signup/UsermailConfirm_Save_OV_029_039.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<formatter 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
			xsi:noNamespaceSchemaLocation="../fwnScheme.xsd">

	<destino nombre="USER_ID">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001010" tipoDatoValor="BigDecimal" />
	</destino>
	<destino nombre="USER_FISTNAME">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001020" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_SURNAME">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001030" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_MAIL">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001040" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_MAIL_ID">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001041" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_PASSWORD">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001050" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_ENTITY_ID">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001060" tipoDatoValor="BigDecimal" />
	</destino>
	<destino nombre="USER_ENTITY_NAME">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001061" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_ACCOUNTTYPE_ID">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001070" tipoDatoValor="BigDecimal" />
	</destino>
	<destino nombre="USER_ACCOUNTTYPE_NAME">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001071" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_STATUS">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001080" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_CREDITCARD_NUMBER">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001090" tipoDatoValor="BigDecimal" />
	</destino>
	<destino nombre="USER_CREDITCARD_EXPIRATION">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001100" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_SIGNUPCODE">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001110" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_NICKNAME">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001120" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_FULLNAME">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001121" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_DISPLAYNAME">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001122" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_AVATARBUILDER_UMD5">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001130" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_USERGROUP_ID">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001140" tipoDatoValor="BigDecimal" />
	</destino>
	<destino nombre="USER_USERGROUP">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001141" tipoDatoValor="String" />
	</destino>

</formatter>

=== adele-robots/fiona/FIOPRE/WebContent/WEB-INF/formatter/sparkStore/FIOPRE_ListSparksByCriteria_VV_029_023.xml
<?xml version="1.0" encoding="UTF-8"?>

<formatter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../fwnScheme.xsd">  
  
  <destino persist="spark_criterio">
    <origen nombre="spark_criterio" />
  </destino>
  
   <destino nombre="SECURE_USERID">
    <origen nombre="SECURE_USERID" />
  </destino>
  
  <destino persist="pulsado_top">
    <origen nombre="pulsado_top" />
  </destino>
  
 <destino persist="pulsado_latest">
    <origen nombre="pulsado_latest" />
  </destino>
  
  <destino persist="pulsado_basic">
    <origen nombre="pulsado_basic" />
  </destino>
  
  <destino persist="sucessBuy" tipoDato="BigDecimal">
	<funcion method="FuncionConstante">
		<origen nombre="" />
	</funcion>
  </destino>
  
</formatter>

=== adele-robots/fiona/FIOPRE/WebContent/WEB-INF/formatter/sparkStore/FIOPRE_SaveSpark_VO_029_033.xml
<?xml version="1.0" encoding="UTF-8"?>

<formatter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../fwnScheme.xsd">  

		<destino nombre="00" tipoDato="BigDecimal">
			<origen nombre="spark_id"/>
		</destino>

		<destino nombre="01" tipoDato="String">
			<origen nombre="nombre"/>
		</destino>

		<destino nombre="02" tipoDato="String">
			<origen nombre="descripcion" />
		</destino>
		
		<destino nombre="03" tipoDato="String">
			<origen nombre="version"/>
		</destino>
		
		<destino nombre="04" tipoDato="String">
			<origen nombre="descCorta"/>
		</destino>
		
		<destino nombre="05" tipoDato="String">
			<origen nombre="novedades"/>
		</destino>
		
		<destino nombre="06" tipoDato="String">
			<origen nombre="otrosKeywords" />
		</destino>
		
		<destino nombre="07" tipoDato="String">
			<origen nombre="email"/>
		</destino>
		
		<destino nombre="08"  tipoDato="String">
			<origen nombre="marketingURL"/>
		</destino>
				
		<destino nombre="09" tipoDato="String">
			<origen nombre="esTrial"/>
		</destino>
		
		<destino nombre="10" tipoDato="BigDecimal">
			<origen nombre="diasTrial"/>
		</destino>
		
		<destino nombre="11" tipoDato="String">
			<origen nombre="icono" />
		</destino>
		
		<destino nombre="12" tipoDato="String">
			<origen nombre="banner"/>
		</destino>
		
		<destino nombre="13" tipoDato="String">
			<origen nombre="video"/>
		</destino>
		
		<destino nombre="14" tipoDato="String">
			<origen nombre="idsKeywords"/>
		</destino>
		<!-- 
		<destino nombre="15" tipoDato="BigDecimal">
			<origen nombre="eulaId"/>
		</destino>  -->
		
		<destino nombre="16" tipoDato="String">
			<origen nombre="idTarifa"/>
		</destino>
		
		<destino nombre="17" tipoDato="String">
			<origen nombre="idTarifaProd"/>
		</destino>
		
		<destino nombre="18" tipoDato="String">
			<origen nombre="emailPaypal"/>
		</destino>
	
</formatter>

=== adele-robots/fiona/FIOPRE/WebContent/WEB-INF/formatter/sparkStore/FIOPRE_ListCrashLogs_OV_029_031.xml
<?xml version="1.0" encoding="UTF-8"?>

<formatter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../fwnScheme.xsd">  

	<componenteIterativo nombre="crashTabla"
		persist="crashList">

		<destino nombre="crash_id">
			<origen nombre="FIONEGN011" tipoDatoValor="BigDecimal"
				propiedadValor="FIONEG011010" />
		</destino>	
		
		<destino nombre="crash_date">
			<origen nombre="FIONEGN011" tipoDatoValor="String"
				propiedadValor="FIONEG011030" />
		</destino>
		
		<destino nombre="crash_motivo">
			<origen nombre="FIONEGN011" tipoDatoValor="String"
				propiedadValor="FIONEG011040" />
		</destino>		
		

	</componenteIterativo>	

	
</formatter>
