=== adele-robots/fiona/FIOPRE/WebContent/WEB-INF/formatter/fwnScheme.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

<xs:element name="formatter">
  <xs:complexType>
	<xs:choice maxOccurs="unbounded">
		<xs:element name="destino" type="fieldType"></xs:element>
		<xs:element name="componenteIterativo">
			<xs:complexType>
				<xs:sequence maxOccurs="unbounded">
					<xs:element name="destino" type="fieldTypeLista" />
				</xs:sequence>
				<xs:attribute name="nombre" use="required"
					type="xs:string" />
				<xs:attribute name="persist" use="optional"
					type="xs:string" />
				<xs:attribute name="sesion" use="optional"
					type="xs:string" />
			</xs:complexType>
		</xs:element>
		<xs:element name="contexto" type="contextoType"></xs:element>
	</xs:choice>
  </xs:complexType>
</xs:element>



<xs:simpleType name="datoType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="String"/>
    <xs:enumeration value="BigDecimal"/>
	<xs:enumeration value="Producto"/>
    <xs:enumeration value="Registro"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="datoTypeSN">
  <xs:restriction base="xs:string">
    <xs:enumeration value="String"/>
    <xs:enumeration value="BigDecimal"/>
    <xs:enumeration value="Date"/>
	<xs:enumeration value="Producto"/>
	<xs:enumeration value="Contexto"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="datoTypeCtx">
  <xs:restriction base="xs:string">
    <xs:enumeration value="String"/>
    <xs:enumeration value="BigDecimal"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="funciones">
  <xs:restriction base="xs:string">
    <xs:enumeration value="FuncionConcatenar"/>
    <xs:enumeration value="FuncionComparar"/>
    <xs:enumeration value="FuncionSuma"/>
    <xs:enumeration value="FuncionResta"/>
    <xs:enumeration value="FuncionMultiplica"/>
    <xs:enumeration value="FuncionDivide"/>
    <xs:enumeration value="FuncionSubString"/>
    <xs:enumeration value="FuncionMayusculas"/>
    <xs:enumeration value="FuncionMinusculas"/>
    <xs:enumeration value="FuncionCompletar"/>
    <xs:enumeration value="FuncionConstante"/>
    <xs:enumeration value="FuncionCuenta"/>
  </xs:restriction>
</xs:simpleType>


<xs:complexType name="fieldType">
	 <xs:choice>
	            <xs:element name="origen">
	            	<xs:complexType>
	            		<xs:sequence>
	            			<xs:element name="registro"
	            				type="registroType" maxOccurs="1" minOccurs="0">
	            			</xs:element>
	            			<xs:element name="registroIterativo"
	            				type="registroIterativoType" maxOccurs="1" minOccurs="0">
	            			</xs:element>
	            		</xs:sequence>
	            		<xs:attribute name="nombre" use="required"
	            			type="xs:string">
	            		</xs:attribute>
	            		<xs:attribute name="tipoDatoValor"
	            			use="optional" type="datoType">
	            		</xs:attribute>
	            		<xs:attribute name="propiedadValor"
	            			use="optional" type="xs:string">
	            		</xs:attribute>
	            	</xs:complexType>
	            </xs:element>
	            <xs:element name="funcion">
           	        	 <xs:complexType>
           	        	      <xs:sequence>
			            		  <xs:element name="origen" maxOccurs="unbounded">
					            	<xs:complexType>
					            		<xs:attribute name="nombre" use="required" type="xs:string"/>
					            	    <xs:attribute name="tipoDatoValor" use="optional" type="datoType"> </xs:attribute>
	            						<xs:attribute name="propiedadValor" use="optional" type="xs:string"> </xs:attribute>
					            	</xs:complexType>
	           					  </xs:element>
           					  </xs:sequence>
           	        	    <xs:attribute name="method" use="required" type="funciones"/>
           	       		 </xs:complexType>
           	    </xs:element>
	</xs:choice>
  <xs:attribute name="nombre" use="optional" type="xs:string"/>
  <xs:attribute name="tipoDato" use="optional" type="datoTypeSN" />
  <xs:attribute name="persist" use="optional" type="xs:string" />
   <xs:attribute name="sesion" use="optional" type="xs:string" />
</xs:complexType>

<xs:complexType name="fieldTypeLista">
	 <xs:sequence>
	            <xs:element name="origen">
	            	<xs:complexType>
	            		<xs:sequence>
	            			<xs:element name="registro"
	            				type="registroType" maxOccurs="1" minOccurs="0">
	            			</xs:element>
	            			<xs:element name="registroIterativo"
	            				type="registroIterativoType" maxOccurs="1" minOccurs="0">
	            			</xs:element>
	            		</xs:sequence>
	            		<xs:attribute name="nombre" use="required"
	            			type="xs:string">
	            		</xs:attribute>
	            		<xs:attribute name="tipoDatoValor"
	            			use="required" type="datoType">
	            		</xs:attribute>
	            		<xs:attribute name="propiedadValor"
	            			use="required" type="xs:string">
	            		</xs:attribute>
	            		<xs:attribute name="tipoDatoEtiqueta"
	            			type="datoType">
	            		</xs:attribute>
	            		<xs:attribute name="propiedadEtiqueta"
	            			type="xs:string">
	            		</xs:attribute>
	            	</xs:complexType>
	            </xs:element>
	</xs:sequence>
  <xs:attribute name="nombre" use="required" type="xs:string"/>
</xs:complexType>


    <xs:complexType name="registroType">
    	<xs:attribute name="propiedadValor" type="xs:string"></xs:attribute>
    	<xs:attribute name="tipoDatoValor" type="datoTypeCtx"></xs:attribute>
    	<xs:attribute name="nombre" type="xs:string"></xs:attribute>
    	<xs:attribute name="tipoDatoEtiqueta" type="datoTypeCtx"></xs:attribute>
    	<xs:attribute name="propiedadEtiqueta" type="xs:string"></xs:attribute>
    </xs:complexType>


    <xs:complexType name="registroIterativoType">
    	<xs:sequence>
    		<xs:element name="registro" type="registroType" maxOccurs="unbounded" minOccurs="1"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="contextoType">
    	<xs:sequence>
    		<xs:element name="destino" type="destinoCtxType" maxOccurs="unbounded" minOccurs="0"></xs:element>
    		<xs:element name="registro" type="registroEntrType" maxOccurs="unbounded" minOccurs="0"></xs:element>
    		<xs:element name="registroIterativo" type="registroIterativoEntrType" maxOccurs="unbounded" minOccurs="0"></xs:element>
    	</xs:sequence>
    	<xs:attribute name="refCtx" type="xs:string"></xs:attribute>
    	<xs:attribute name="nombreCtx" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="registroEntrType">
    	<xs:sequence>
    		<xs:element name="destino" type="destinoCtxType" maxOccurs="unbounded" minOccurs="0"></xs:element>
    		<xs:element name="registro" type="registroEntrType" maxOccurs="unbounded" minOccurs="0"></xs:element>
    		<xs:element name="registroIterativo" type="registroIterativoEntrType" maxOccurs="unbounded" minOccurs="0"></xs:element>
    	</xs:sequence>
    	<xs:attribute name="nombreReg" type="xs:string"></xs:attribute>
    </xs:complexType>
    
    <xs:complexType name="registroIterativoEntrType">
    	<xs:sequence>
    		<xs:element name="registro" type="registroEntrType"
    			maxOccurs="unbounded" minOccurs="0">
    		</xs:element>
    	</xs:sequence>
    	<xs:attribute name="nombre" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="destinoCtxType">
    	<xs:sequence>
    		<xs:element name="origen" type="OrigenCtxType" maxOccurs="1" minOccurs="1"></xs:element>
    	</xs:sequence>
    	<xs:attribute name="propiedadValor" type="xs:string"></xs:attribute>
    	<xs:attribute name="tipoDatoValor" type="datoTypeCtx"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="tipoDatoValorCtxType"></xs:complexType>

    <xs:complexType name="OrigenCtxType">
    	<xs:attribute name="nombre" type="xs:string"></xs:attribute>
    </xs:complexType>
</xs:schema>

=== adele-robots/fiona/FIOPRE/WebContent/WEB-INF/formatter/myprofile/MyProfile_Save_VV_029_002.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<formatter 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:noNamespaceSchemaLocation="../fwnScheme.xsd">

	<destino persist="USER_FISTNAME" sesion="SES_USER_FISTNAME">
		<origen nombre="USER_FISTNAME" />
	</destino>
	<destino persist="USER_SURNAME" sesion="SES_USER_SURNAME">
		<origen nombre="USER_SURNAME" />
	</destino>	
	<destino persist="USER_MAIL" sesion="SES_USER_MAIL">
		<origen nombre="USER_MAIL" />
	</destino>	
	<destino persist="USER_NEWPASSWORD1" sesion="SES_USER_NEWPASSWORD1">
		<origen nombre="USER_NEWPASSWORD1" />
	</destino>	
	<destino persist="USER_ACCOUNTTYPE_ID" sesion="SES_USER_ACCOUNTTYPE_ID">
		<origen nombre="USER_ACCOUNTTYPE_ID" />
	</destino>	
	<destino persist="USER_NICKNAME" sesion="SES_USER_NICKNAME">
		<origen nombre="USER_NICKNAME" />
	</destino>
	<destino persist="SECURE_USER_USERGROUP_ID">
		<!-- El propio usuario no puede cambiar su rol asi que lo cogemos de session -->
		<origen nombre="SECURE_USER_USERGROUP_ID" />
	</destino>
	<destino persist="USER_TITLE" sesion="SES_USER_TITLE">
		<origen nombre="USER_TITLE" />
	</destino>
	<destino persist="USER_FLAGENTITY" sesion="SES_USER_FLAGENTITY">
		<origen nombre="USER_FLAGENTITY" />
	</destino>
	<destino persist="USER_ORGANIZATIONTYPE_ID" sesion="SES_USER_ORGANIZATIONTYPE_ID">
		<origen nombre="USER_ORGANIZATIONTYPE_ID" />
	</destino>
	<destino persist="USER_LEGALENTITYNAME" sesion="SES_USER_LEGALENTITYNAME">
		<origen nombre="USER_LEGALENTITYNAME" />
	</destino>
	<destino persist="USER_WEBSITE" sesion="SES_USER_WEBSITE">
		<origen nombre="USER_WEBSITE" />
	</destino>
	<destino persist="USER_WORKEMAIL" sesion="SES_USER_WORKEMAIL">
		<origen nombre="USER_WORKEMAIL" />
	</destino>
	<destino persist="USER_COUNTRYCODE" sesion="SES_USER_COUNTRYCODE">
		<origen nombre="USER_COUNTRYCODE" />
	</destino>
	<destino persist="USER_PHONENUMBER" sesion="SES_USER_PHONENUMBER">
		<origen nombre="USER_PHONENUMBER" />
	</destino>
	<destino persist="USER_EXT" sesion="SES_USER_EXT">
		<origen nombre="USER_EXT" />
	</destino>
	<destino persist="USER_ACCOUNTTYPE_METHOD" sesion="SES_USER_ACCOUNTTYPE_METHOD">
		<origen nombre="USER_ACCOUNTTYPE_METHOD" />
	</destino>
	<destino persist="account_credit" sesion="ses_account_credit">
		<origen nombre="account_credit" />
	</destino>	

</formatter>

=== adele-robots/fiona/FIOPRE/WebContent/WEB-INF/formatter/signup/Signup_Save_VO_029_001.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<formatter 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:noNamespaceSchemaLocation="../fwnScheme.xsd">

	<destino nombre="00" tipoDato="String">
		<origen nombre="USER_FISTNAME" />
	</destino>
	<destino nombre="01" tipoDato="String">
		<origen nombre="USER_SURNAME" />
	</destino>
	<destino nombre="02" tipoDato="String">
		<origen nombre="USER_MAIL" />
	</destino>
	<destino nombre="03" tipoDato="String">
		<origen nombre="USER_PASSWORD1" />
	</destino>
	<destino nombre="04" tipoDato="BigDecimal">
		<origen nombre="USER_ENTITY_ID" />
	</destino>
	<destino nombre="05" tipoDato="BigDecimal">
		<origen nombre="USER_ACCOUNTTYPE_ID" />
	</destino>
	<destino nombre="06" tipoDato="BigDecimal">
		<origen nombre="USER_CREDITCARD_NUMBER" />
	</destino>
	<destino nombre="07" tipoDato="String">
		<origen nombre="USER_CREDITCARD_EXPIRATION" />
	</destino>
	<destino nombre="08" tipoDato="String">
		<origen nombre="USER_NICKNAME" />
	</destino>
	<destino nombre="09" tipoDato="BigDecimal">
		<funcion method="FuncionConstante">
			<origen nombre="2" /><!-- En BBDD es ROLE_USER -->
		</funcion>
	</destino>
	<destino nombre="10" tipoDato="String">
		<origen nombre="USER_TITLE" />
	</destino>
	<destino nombre="11" tipoDato="String">
		<origen nombre="USER_FLAGENTITY" />
	</destino>
	<destino nombre="12" tipoDato="BigDecimal">
		<origen nombre="USER_ORGANIZATIONTYPE_ID" />
	</destino>
	<destino nombre="13" tipoDato="String">
		<origen nombre="USER_LEGALENTITYNAME" />
	</destino>
	<destino nombre="14" tipoDato="String">
		<origen nombre="USER_WEBSITE" />
	</destino>
	<destino nombre="15" tipoDato="String">
		<origen nombre="USER_WORKEMAIL" />
	</destino>
	<destino nombre="16" tipoDato="String">
		<origen nombre="USER_COUNTRYCODE" />
	</destino>
	<destino nombre="17" tipoDato="String">
		<origen nombre="USER_PHONENUMBER" />
	</destino>
	<destino nombre="18" tipoDato="String">
		<origen nombre="USER_EXT" />
	</destino>
	<destino nombre="19" tipoDato="String">
		<origen nombre="USER_ACCOUNTTYPE_METHOD" />
	</destino>

</formatter>

=== adele-robots/fiona/FIOPRE/WebContent/WEB-INF/formatter/sparkStore/FIOPRE_ListSparksDeveloper_OV_029_028.xml
<?xml version="1.0" encoding="UTF-8"?>

<formatter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../fwnScheme.xsd">  

	<componenteIterativo nombre="sparksTabla"
		persist="sparksDeveloper">

		<destino nombre="spark_id">
			<origen nombre="FIONEGN004" tipoDatoValor="BigDecimal"
				propiedadValor="FIONEG004010" />
		</destino>

		<destino nombre="nombre">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004020" />
		</destino>	
		
		<destino nombre="status_id">
			<origen nombre="FIONEGN004" tipoDatoValor="BigDecimal"
				propiedadValor="FIONEG004200" />
		</destino>		
		
		<destino nombre="status_nombre">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004210" />
		</destino>	
		
		<destino nombre="iconPath">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004230" />
		</destino>
		
		<destino nombre="statusDate">
			<origen nombre="FIONEGN004" tipoDatoValor="String"
				propiedadValor="FIONEG004240" />
		</destino>
	

	</componenteIterativo>	

	
</formatter>

=== adele-robots/fiona/FIOPRE/WebContent/WEB-INF/formatter/sparkStore/FIOPRE_ListRejectionDetails_OV_029_030.xml
<?xml version="1.0" encoding="UTF-8"?>

<formatter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../fwnScheme.xsd">  

	<componenteIterativo nombre="rejectionTabla"
		persist="rejectionList">

		<destino nombre="rejection_id">
			<origen nombre="FIONEGN010" tipoDatoValor="BigDecimal"
				propiedadValor="FIONEG010010" />
		</destino>	
		
		<destino nombre="rejection_date">
			<origen nombre="FIONEGN010" tipoDatoValor="String"
				propiedadValor="FIONEG010030" />
		</destino>
		
		<destino nombre="rejection_motivo">
			<origen nombre="FIONEGN010" tipoDatoValor="String"
				propiedadValor="FIONEG010040" />
		</destino>		
		

	</componenteIterativo>	

	
</formatter>

=== adele-robots/fiona/FIOPRE/WebContent/WEB-INF/formatter/myprofile/MyProfile_Edit_SV.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<formatter 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
			xsi:noNamespaceSchemaLocation="../fwnScheme.xsd">

	<destino nombre="USER_ID">
		<origen nombre="SECURE_USERID" />
	</destino>
	<destino nombre="USER_FISTNAME">
		<origen nombre="SECURE_USER_FISTNAME" />
	</destino>
	<destino nombre="USER_SURNAME">
		<origen nombre="SECURE_USER_SURNAME" />
	</destino>
	<destino nombre="USER_MAIL">
		<origen nombre="SECURE_USERMAIL" />
	</destino>
	<destino nombre="USER_MAIL_ID">
		<origen nombre="SECURE_USERMAIL_ID" />
	</destino>
	<destino nombre="CHANGEMYPASSWD">
		<funcion method="FuncionConstante">
			<origen nombre="false" />
		</funcion>
	</destino>
	<destino nombre="USER_PASSWORD">
		<funcion method="FuncionConstante">
			<origen nombre="" />
		</funcion>
	</destino>
	<destino nombre="USER_NEWPASSWORD1">
		<funcion method="FuncionConstante">
			<origen nombre="" />
		</funcion>
	</destino>
	<destino nombre="USER_NEWPASSWORD2">
		<funcion method="FuncionConstante">
			<origen nombre="" />
		</funcion>
	</destino>
	<destino nombre="USER_ENTITY_ID">
		<origen nombre="SECURE_USER_ENTITY_ID" />
	</destino>
	<destino nombre="USER_ENTITY_NAME">
		<origen nombre="SECURE_USER_ENTITY_NAME" />
	</destino>
	<destino nombre="USER_ACCOUNTTYPE_ID">
		<origen nombre="SECURE_USER_ACCOUNTTYPE_ID" />
	</destino>
	<destino nombre="USER_ACCOUNTTYPE_NAME">
		<origen nombre="SECURE_USER_ACCOUNTTYPE_NAME" />
	</destino>
	<destino nombre="USER_STATUS">
		<origen nombre="SECURE_USER_STATUS" />
	</destino>
	<destino nombre="USER_CREDITCARD_NUMBER">
		<origen nombre="SECURE_USER_CREDITCARD_NUMBER" />
	</destino>
	<destino nombre="USER_CREDITCARD_EXPIRATION">
		<origen nombre="SECURE_USER_CREDITCARD_EXPIRATION" />
	</destino>
	<destino nombre="USER_SIGNUPCODE">
		<origen nombre="SECURE_USER_SIGNUPCODE" />
	</destino>
	<destino nombre="USER_NICKNAME">
		<origen nombre="SECURE_USER_NICKNAME" />
	</destino>
	<destino nombre="USER_FULLNAME">
		<origen nombre="SECURE_USER_FULLNAME" />
	</destino>
	<destino nombre="USER_DISPLAYNAME">
		<origen nombre="SECURE_USER_DISPLAYNAME" />
	</destino>
	<destino nombre="USER_AVATARBUILDER_UMD5">
		<origen nombre="SECURE_USERMAILD5" />
	</destino>
	<destino nombre="USER_USERGROUP_ID">
		<origen nombre="SECURE_USER_USERGROUP_ID" />
	</destino>
	<destino nombre="USER_USERGROUP">
		<origen nombre="SECURE_USER_USERGROUP" />
	</destino>
	<destino nombre="USER_TITLE">
		<origen nombre="SECURE_USER_TITLE" />
	</destino>
	<destino nombre="USER_FLAGENTITY">
		<origen nombre="SECURE_USER_FLAG_ENTITY" />
	</destino>
	<destino nombre="USER_BILLING_AGREEMENT_ID">
		<origen nombre="SECURE_USER_BILLING_AGREEMENT_ID" />
	</destino>
	<destino nombre="USER_ACCOUNTTYPE_METHOD">
		<origen nombre="SECURE_USER_ACCOUNTTYPE_METHOD" />
	</destino>
	<destino nombre="account_credit">
		<origen nombre="SECURE_USER_ACCOUNT_CREDIT"></origen>
	</destino>
	<destino nombre="FLAG_CERT">
		<origen nombre="SECURE_FLAG_CERT"></origen>
	</destino>
	<destino nombre="USER_LEGALENTITYNAME">
		<origen nombre="FIONEGN027" propiedadValor="FIONEG027020" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_ORGANIZATIONTYPE_ID">
		<origen nombre="FIONEGN027" propiedadValor="FIONEG027030" tipoDatoValor="BigDecimal" />
	</destino>
	<destino nombre="USER_WEBSITE">
		<origen nombre="FIONEGN027" propiedadValor="FIONEG027040" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_WORKEMAIL">
		<origen nombre="FIONEGN027" propiedadValor="FIONEG027050" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_COUNTRYCODE">
		<origen nombre="FIONEGN027" propiedadValor="FIONEG027060" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_PHONENUMBER">
		<origen nombre="FIONEGN027" propiedadValor="FIONEG027070" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_EXT">
		<origen nombre="FIONEGN027" propiedadValor="FIONEG027080" tipoDatoValor="String" />
	</destino>
	

</formatter>

=== adele-robots/fiona/FIOPRE/WebContent/WEB-INF/formatter/sparkStore/FIOPRE_ListStatus_OV_029_029.xml
<?xml version="1.0" encoding="UTF-8"?>

<formatter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../fwnScheme.xsd">  

	<componenteIterativo nombre="statusTabla"
		persist="statusList">

		<destino nombre="status_id">
			<origen nombre="FIONEGN009" tipoDatoValor="BigDecimal"
				propiedadValor="FIONEG009010" />
		</destino>	
		
		<destino nombre="status_date">
			<origen nombre="FIONEGN009" tipoDatoValor="String"
				propiedadValor="FIONEG009030" />
		</destino>
		
		<destino nombre="status_nombre">
			<origen nombre="FIONEGN009" tipoDatoValor="String"
				propiedadValor="FIONEG009050" />
		</destino>	
		
		<destino nombre="status_nombre_usuario">
			<origen nombre="FIONEGN009" tipoDatoValor="String"
				propiedadValor="FIONEG009060" />
		</destino>		
		

	</componenteIterativo>	

	
</formatter>

=== adele-robots/fiona/FIOPRE/WebContent/WEB-INF/formatter/signup/Signup_Save_OV_029_065.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<formatter 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
			xsi:noNamespaceSchemaLocation="../fwnScheme.xsd">

	<destino persist="USER_ID" sesion="SECURE_USERID">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001010" tipoDatoValor="BigDecimal" />
	</destino>
	<destino nombre="USER_FISTNAME" sesion="SECURE_USER_FISTNAME">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001020" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_SURNAME" sesion="SECURE_USER_SURNAME">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001030" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_MAIL" sesion="SECURE_USERMAIL">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001040" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_MAIL_ID" sesion="SECURE_USERMAIL_ID">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001041" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_PASSWORD"  sesion="SECURE_USER_PASSWORD">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001050" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_ENTITY_ID" sesion="SECURE_USER_ENTITY_ID">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001060" tipoDatoValor="BigDecimal" />
	</destino>
	<destino nombre="USER_ENTITY_NAME" sesion="SECURE_USER_ENTITY_NAME">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001061" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_ACCOUNTTYPE_ID" sesion="SECURE_USER_ACCOUNTTYPE_ID">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001070" tipoDatoValor="BigDecimal" />
	</destino>
	<destino nombre="USER_ACCOUNTTYPE_NAME" sesion="SECURE_USER_ACCOUNTTYPE_NAME">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001071" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_STATUS" sesion="SECURE_USER_STATUS">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001080" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_CREDITCARD_NUMBER" sesion="SECURE_USER_CREDITCARD_NUMBER">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001090" tipoDatoValor="BigDecimal" />
	</destino>
	<destino nombre="USER_CREDITCARD_EXPIRATION" sesion="SECURE_USER_CREDITCARD_EXPIRATION">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001100" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_SIGNUPCODE" sesion="SECURE_USER_SIGNUPCODE">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001110" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_NICKNAME" sesion="SECURE_USER_NICKNAME">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001120" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_FULLNAME" sesion="SECURE_USER_FULLNAME">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001121" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_DISPLAYNAME" sesion="SECURE_USER_DISPLAYNAME">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001122" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_AVATARBUILDER_UMD5" sesion="SECURE_USERMAILD5">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001130" tipoDatoValor="String" />
	</destino>
	<destino nombre="USER_USERGROUP_ID" sesion="SECURE_USER_USERGROUP_ID">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001140" tipoDatoValor="BigDecimal" />
	</destino>
	<destino nombre="USER_USERGROUP" sesion="SECURE_USER_USERGROUP">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001141" tipoDatoValor="String" />
	</destino>
	<destino nombre="ACCOUNT_PERIOD" sesion="SECURE_USER_ACCOUNTTYPE_METHOD">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001190" tipoDatoValor="String" />
	</destino>
	<destino nombre="BILLING_AGREEMENT_ID" sesion="SECURE_USER_BILLING_AGREEMENT_ID">
		<origen nombre="FIONEGN001" propiedadValor="FIONEG001200" tipoDatoValor="String" />
	</destino>
	

</formatter>

=== adele-robots/fiona/FIOPRE/WebContent/WEB-INF/formatter/signup/Signup_Setup_OV.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<formatter 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
			xsi:noNamespaceSchemaLocation="../fwnScheme.xsd">

	<destino nombre="USER_ID">
		<funcion method="FuncionConstante">
			<origen nombre="" />
		</funcion>
	</destino>
	<destino nombre="USER_FISTNAME">
		<funcion method="FuncionConstante">
			<origen nombre="" />
		</funcion>
	</destino>
	<destino nombre="USER_SURNAME">
		<funcion method="FuncionConstante">
			<origen nombre="" />
		</funcion>
	</destino>
	<destino nombre="USER_MAIL">
		<funcion method="FuncionConstante">
			<origen nombre="" />
		</funcion>
	</destino>
	<destino nombre="USER_MAIL_ID">
		<funcion method="FuncionConstante">
			<origen nombre="" />
		</funcion>
	</destino>
	<destino nombre="USER_PASSWORD1">
		<funcion method="FuncionConstante">
			<origen nombre="" />
		</funcion>
	</destino>
	<destino nombre="USER_PASSWORD2">
		<funcion method="FuncionConstante">
			<origen nombre="" />
		</funcion>
	</destino>
	<destino nombre="USER_ENTITY_ID">
		<funcion method="FuncionConstante">
			<origen nombre="" />
		</funcion>
	</destino>
	<destino nombre="USER_ENTITY_NAME">
		<funcion method="FuncionConstante">
			<origen nombre="" />
		</funcion>
	</destino>
	<destino nombre="USER_ACCOUNTTYPE_ID">
		<funcion method="FuncionConstante">
			<origen nombre="1" />
		</funcion>
	</destino>
	<destino nombre="USER_ACCOUNTTYPE_NAME">
		<funcion method="FuncionConstante">
			<origen nombre="" />
		</funcion>
	</destino>
	<destino nombre="USER_STATUS">
		<funcion method="FuncionConstante">
			<origen nombre="unconfirmed" />
		</funcion>
	</destino>
	<destino nombre="USER_CREDITCARD_NUMBER">
		<funcion method="FuncionConstante">
			<origen nombre="" />
		</funcion>
	</destino>
	<destino nombre="USER_CREDITCARD_EXPIRATION">
		<funcion method="FuncionConstante">
			<origen nombre="" />
		</funcion>
	</destino>
	<destino nombre="USER_SIGNUPCODE">
		<funcion method="FuncionConstante">
			<origen nombre="" />
		</funcion>
	</destino>
	<destino nombre="USER_NICKNAME">
		<funcion method="FuncionConstante">
			<origen nombre="" />
		</funcion>
	</destino>
	<destino nombre="USER_FULLNAME">
		<funcion method="FuncionConstante">
			<origen nombre="" />
		</funcion>
	</destino>
	<destino nombre="USER_DISPLAYNAME">
		<funcion method="FuncionConstante">
			<origen nombre="" />
		</funcion>
	</destino>
	<destino nombre="USER_AVATARBUILDER_UMD5">
		<funcion method="FuncionConstante">
			<origen nombre="" />
		</funcion>
	</destino>
	<destino nombre="USER_USERGROUP_ID">
		<funcion method="FuncionConstante">
			<origen nombre="2" />
		</funcion>
	</destino>
	<destino nombre="USER_USERGROUP">
		<funcion method="FuncionConstante">
			<origen nombre="USER" />
		</funcion>
	</destino>
	<destino nombre="USER_FLAGENTITY">
		<funcion method="FuncionConstante">
			<origen nombre="0" />
		</funcion>
	</destino>

</formatter>
