=== adele-robots/fiona/SPARKS/ApplicationDataDevelopment/Plugins/ComponentNetwork.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="ComponentNetwork" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
  <xs:element name="Interface">
    <xs:complexType>
      <xs:attribute name="name" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="ComponentNetwork" msdata:IsDataSet="true" msdata:Locale="en-US">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="Interface" />
        <xs:element name="ComponentDeclarations">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Component" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="ProvidedInterfaces" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element ref="Interface" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="RequiredInterfaces" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element ref="Interface" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Parameters" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Parameter" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="name" type="xs:string" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string" />
                  <xs:attribute name="type" type="xs:string" />
                  <xs:attribute name="plugin" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="ApplicationDescription">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ComponentInstances" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Instance" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="ParameterValues" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="assing" minOccurs="0" maxOccurs="unbounded">
                                  <xs:complexType>
                                    <xs:attribute name="parameter" type="xs:string" />
                                    <xs:attribute name="value" type="xs:string" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="instanceName" type="xs:string" />
                        <xs:attribute name="componentID" type="xs:string" />
                        <xs:attribute name="config" type="xs:string" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="InterfaceConnections" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Connect" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="interface" type="xs:string" />
                        <xs:attribute name="providedBy" type="xs:string" />
                        <xs:attribute name="requiredBy" type="xs:string" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== adele-robots/fiona/SPARKS/Run/xml/testParaLinux.xml
<?xml version="1.0" encoding="utf-8"?>
<ComponentNetwork xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ComponentNetwork.xsd">

    <!-- COMPONENT DECLARATION -->
  <ComponentDeclarations>
    <Component  id="idScene3DComponent"  type="Scene3DComponent" plugin="libScene3DSpark.so">
      <ProvidedInterfaces>
        <Interface name="IFaceExpression" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="IEyes" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="INeck" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="IAnimation" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="IRenderizable" />
      </ProvidedInterfaces>
    </Component>

    <Component id="idThread"  type="ThreadComponent" plugin="libThreadSpark.so">
      <ProvidedInterfaces>
        <Interface name="IConcurrent" />
      </ProvidedInterfaces>
      <RequiredInterfaces>
        <Interface name="IAsyncFatalErrorHandler" />
        <Interface name="IThreadProc" />
      </RequiredInterfaces>
    </Component>

    <Component id="idLocalRendererComponent"  type="LocalRendererComponent" plugin="libLocalRendererSpark.so">
      <ProvidedInterfaces>
        <Interface name="IThreadProc" />
      </ProvidedInterfaces>
      <RequiredInterfaces>
        <Interface name="IAsyncFatalErrorHandler" />
        <Interface name="IFrameBuffer" />
        <Interface name="IRenderizable" />
		<Interface name="IUpdateable" />
      </RequiredInterfaces>
    </Component>

    <Component id="idWindowComponent"  type="WindowComponent" plugin="libWindowSpark.so">
      <ProvidedInterfaces>
        <Interface name="IApplication" />
        <Interface name="IWindow" />
		<Interface name="IEventQueue" />
        <Interface name="IAsyncFatalErrorHandler" />
      </ProvidedInterfaces>
    </Component>


	

	
	<Component id="idEyeContactComponent"  type="EyeContactComponent" plugin="libEyeContactSpark.so">
      <ProvidedInterfaces>
        <Interface name="IDetectedFacePositionConsumer" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IUpdateable1" />
      </ProvidedInterfaces>
      <RequiredInterfaces>
        <Interface name="INeck" />
        <Interface name="IEyes" />
      </RequiredInterfaces>
    </Component>
	
	<Component id="idUpdater1"  type="Updater1" plugin="libUpdaterSpark.so">
      <ProvidedInterfaces>
        <Interface name="IUpdateable" />
      </ProvidedInterfaces>
	    <RequiredInterfaces>
        <Interface name="IUpdateable1" />
      </RequiredInterfaces>
    </Component>
	

	
  </ComponentDeclarations>
  
  
  <!-- APPLICATION DESCRIPTION -->
  <ApplicationDescription applicationComponent="instanceWindowComponent" applicationConfig="/Eca.ini">
    <!-- Paso 1/2: Instantiate components -->
    <ComponentInstances>
      <Instance instanceName="instanceWindowComponent" componentID ="idWindowComponent"/>
      <Instance instanceName="instanceScene3DComponent" componentID ="idScene3DComponent"/>
      <Instance instanceName="instanceRenderingThread" componentID ="idThread"/>
      <Instance instanceName="instanceLocalRendererComponent" componentID ="idLocalRendererComponent"/>
      <Instance instanceName="instanceEyeContactComponent" componentID ="idEyeContactComponent"/>
      <Instance instanceName="instanceUpdater1" componentID ="idUpdater1"/>
    </ComponentInstances>
    
    <!-- Paso 2/2: Connect interfaces -->
    <InterfaceConnections>
      <Connect interface="IWindow" providedBy="instanceWindowComponent" requiredBy="instanceLocalRendererComponent" />
	 
      <Connect interface="IThreadProc" providedBy="instanceLocalRendererComponent" requiredBy="instanceRenderingThread" />
      <Connect interface="IRenderizable" providedBy="instanceScene3DComponent" requiredBy="instanceLocalRendererComponent" />
	  
	  <Connect interface="IEyes" providedBy="instanceScene3DComponent" requiredBy="instanceEyeContactComponent" />
	  <Connect interface="INeck" providedBy="instanceScene3DComponent" requiredBy="instanceEyeContactComponent" />
	  
	  <Connect interface="IUpdateable1" providedBy="instanceEyeContactComponent" requiredBy="instanceUpdater1" />
	  <Connect interface="IUpdateable" providedBy="instanceUpdater1" requiredBy="instanceLocalRendererComponent" />
	   
      
	 
	  
      <ConnectAll interface="IAsyncFatalErrorHandler" providedBy="instanceWindowComponent"/>
    </InterfaceConnections>
  </ApplicationDescription>
</ComponentNetwork>

=== adele-robots/fiona/SPARKS/Run/xml/testCE3DC_Updater.xml
<?xml version="1.0" encoding="utf-8"?>
<ComponentNetwork xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ComponentNetwork.xsd">

    <!-- COMPONENT DECLARATION -->
  <ComponentDeclarations>
    <Component  id="idCharacterEmbodiment3DComponent"  type="CharacterEmbodiment3DSpark" plugin="libCharacterEmbodiment3DSpark.so">
      <ProvidedInterfaces>
        <Interface name="IFaceExpression" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="IEyes" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="INeck" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="IAnimation" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IConcurrent" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IAsyncFatalErrorHandler" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IApplication" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IEventQueue" />
      </ProvidedInterfaces>

	<ProvidedInterfaces>
        <Interface name="IFrameEventPublisher" />
      </ProvidedInterfaces>

	  <RequiredInterfaces>
		<Interface name="IAsyncFatalErrorHandler" />
      </RequiredInterfaces>
    </Component>

    
	
	<Component id="idEyeContactComponent"  type="EyeContactSpark" plugin="libEyeContactSpark.so">
      <ProvidedInterfaces>
        <Interface name="IDetectedFacePositionConsumer" />
      </ProvidedInterfaces>
	
      <RequiredInterfaces>
        <Interface name="INeck" />
        <Interface name="IEyes" />
	<Interface name="IFrameEventPublisher" />
      </RequiredInterfaces>
    </Component>
	
	
	
  </ComponentDeclarations>
  
  
  <!-- APPLICATION DESCRIPTION -->
  <ApplicationDescription applicationComponent="instanceCharacterEmbodiment3DComponent" applicationConfig="/GeneralEca.ini">
    <!-- Paso 1/2: Instantiate components -->
    <ComponentInstances>
      			
	  <Instance instanceName="instanceCharacterEmbodiment3DComponent" componentID ="idCharacterEmbodiment3DComponent" configuration="/ComponentConfigurations/CharacterEmbodiment3DSpark.ini"	/>
	  <Instance instanceName="instanceEyeContactComponent" componentID ="idEyeContactComponent" configuration="/ComponentConfigurations/EyeContactSpark.ini" />
	 
	  
	  
    </ComponentInstances>
    
    <!-- Paso 2/2: Connect interfaces -->
    <InterfaceConnections>
	  
	  <Connect interface="IEyes" providedBy="instanceCharacterEmbodiment3DComponent"
requiredBy="instanceEyeContactComponent" />
	  <Connect interface="INeck" providedBy="instanceCharacterEmbodiment3DComponent" requiredBy="instanceEyeContactComponent" />
	  
	
      <ConnectAll interface="IFrameEventPublisher" providedBy="instanceCharacterEmbodiment3DComponent"/>
      <ConnectAll interface="IAsyncFatalErrorHandler" providedBy="instanceCharacterEmbodiment3DComponent"/>
    </InterfaceConnections>
  </ApplicationDescription>
</ComponentNetwork>

=== adele-robots/fiona/SPARKS/Run/xml/testRCE3DNoVoiceC_Subscriber.xml
<?xml version="1.0" encoding="utf-8"?>
<ComponentNetwork xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ComponentNetwork.xsd">

    <!-- COMPONENT DECLARATION -->
  <ComponentDeclarations>
    <Component  id="idRemoteCharacterEmbodiment3DSpark"  type="RemoteCharacterEmbodiment3DSpark" plugin="libRemoteCharacterEmbodiment3DSpark.so">
      <ProvidedInterfaces>
        <Interface name="IFaceExpression" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="IEyes" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="INeck" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="IAnimation" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="ICamera" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IConcurrent" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IAsyncFatalErrorHandler" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IApplication" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IEventQueue" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="IFrameEventPublisher" />
      </ProvidedInterfaces>
      <RequiredInterfaces>
	<Interface name="IAudioQueue" />
	<Interface name="IAsyncFatalErrorHandler" />
	<Interface name="IControlVoice" />
      </RequiredInterfaces>
    </Component>

	
    <Component id="idEyeContactSpark"  type="EyeContactSpark" plugin="libEyeContactSpark.so">
      <ProvidedInterfaces>
        <Interface name="IDetectedFacePositionConsumer" />
      </ProvidedInterfaces>
      <RequiredInterfaces>
        <Interface name="INeck" />
        <Interface name="IEyes" />
	<Interface name="IFrameEventPublisher" />
      </RequiredInterfaces>
    </Component>
	

    <Component id="idTestNoVoiceSpark"  type="TestNoVoiceSpark" plugin="libTestNoVoiceSpark.so">
      <ProvidedInterfaces>
	<Interface name="IControlVoice" />
	<Interface name="IAudioQueue" />	
      </ProvidedInterfaces>
    </Component>

	
 <Component id="idCameraControl"  type="CameraControlSpark" plugin="libCameraControlSpark.so">
      <RequiredInterfaces>
        <Interface name="ICamera" />
	<Interface name="IFrameEventPublisher" />
      </RequiredInterfaces>
    </Component>
	
  </ComponentDeclarations>
  
  
  <!-- APPLICATION DESCRIPTION -->
  <ApplicationDescription applicationComponent="instanceRemoteCharacterEmbodiment3DSpark" applicationConfig="/GeneralEca.ini">
    <!-- Paso 1/2: Instantiate components -->
    <ComponentInstances>
     

	  <Instance instanceName="instanceRemoteCharacterEmbodiment3DSpark" componentID ="idRemoteCharacterEmbodiment3DSpark" configuration="/ComponentConfigurations/CharacterEmbodiment3DSpark.ini"/>
	  
	   <Instance instanceName="instanceEyeContactSpark" componentID ="idEyeContactSpark" configuration="/ComponentConfigurations/EyeContactSpark.ini"/>
	  

	<Instance instanceName="instanceCameraControlSpark" componentID ="idCameraControl" configuration="/ComponentConfigurations/CameraControlSpark.ini"/>
	  <Instance instanceName="instanceTestNoVoiceSpark" componentID ="idTestNoVoiceSpark" configuration="/ComponentConfigurations/VoiceStartSpark.ini"/>
>
	  	  
    </ComponentInstances>
    
    <!-- Paso 2/2: Connect interfaces -->
    <InterfaceConnections>
	  
	  <Connect interface="IEyes" providedBy="instanceRemoteCharacterEmbodiment3DSpark" requiredBy="instanceEyeContactSpark" />
	  <Connect interface="INeck" providedBy="instanceRemoteCharacterEmbodiment3DSpark" requiredBy="instanceEyeContactSpark" />
	  <Connect interface="IAudioQueue" providedBy="instanceTestNoVoiceSpark" requiredBy="instanceRemoteCharacterEmbodiment3DSpark" />
	  

	<Connect interface="IControlVoice" providedBy="instanceTestNoVoiceSpark" requiredBy="instanceRemoteCharacterEmbodiment3DSpark" />


	 <Connect interface="IFaceExpression" providedBy="instanceRemoteCharacterEmbodiment3DSpark" 		     requiredBy="instanceVoiceStartSpark" />

	
	<Connect interface="ICamera" providedBy="instanceRemoteCharacterEmbodiment3DSpark" requiredBy="instanceCameraControlSpark" />
	  
  
      <ConnectAll interface="IAsyncFatalErrorHandler" providedBy="instanceRemoteCharacterEmbodiment3DSpark"/>
      <ConnectAll interface="IFrameEventPublisher" providedBy="instanceRemoteCharacterEmbodiment3DSpark"/>
    </InterfaceConnections>
  </ApplicationDescription>
</ComponentNetwork>

=== adele-robots/fiona/SPARKS/Run/xml/testSinCam.xml
<?xml version="1.0" encoding="utf-8"?>
<ComponentNetwork xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ComponentNetwork.xsd">

    <!-- COMPONENT DECLARATION -->
  <ComponentDeclarations>
    <Component  id="idRemoteCharacterEmbodiment3DSpark"  type="RemoteCharacterEmbodiment3DSpark" plugin="libRemoteCharacterEmbodiment3DSpark.so">
      <ProvidedInterfaces>
        <Interface name="IFaceExpression" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="IEyes" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="INeck" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="IAnimation" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IConcurrent" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IAsyncFatalErrorHandler" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IApplication" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IEventQueue" />
      </ProvidedInterfaces>
      <RequiredInterfaces>
        <Interface name="IUpdateable" />
	<Interface name="IAudioQueue" />
	<Interface name="IAsyncFatalErrorHandler" />
	<Interface name="IControlVoice" />
      </RequiredInterfaces>
    </Component>

    <Component id="idRemoteLoquendoVoiceSpark"  type="RemoteFliteVoiceSpark" plugin="libRemoteFliteVoiceSpark.so">
      <ProvidedInterfaces>
	<Interface name="IVoice" />
	<Interface name="IAudioQueue" />
      </ProvidedInterfaces>
    </Component>

	
    <Component id="idEyeContactSpark"  type="EyeContactSpark" plugin="libEyeContactSpark.so">
      <ProvidedInterfaces>
        <Interface name="IDetectedFacePositionConsumer" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IUpdateable1" />
      </ProvidedInterfaces>
      <RequiredInterfaces>
        <Interface name="INeck" />
        <Interface name="IEyes" />
      </RequiredInterfaces>
    </Component>
	
     <Component id="idUpdater1"  type="Updater1" plugin="libUpdaterSpark.so">
      <ProvidedInterfaces>
        <Interface name="IUpdateable" />
      </ProvidedInterfaces>
      <RequiredInterfaces>
        <Interface name="IUpdateable1" />
	<Interface name="IUpdateable2" />
      </RequiredInterfaces>
    </Component>

    <Component id="idVoiceStartSpark"  type="VoiceStartSpark" plugin="libVoiceStartSpark.so">
      <ProvidedInterfaces>
	<Interface name="IUpdateable2" />
	<Interface name="IControlVoice" />	
      </ProvidedInterfaces>
      <RequiredInterfaces>
        <Interface name="IVoice" />
	<Interface name="IFaceExpression" />
      </RequiredInterfaces>
    </Component>
  		
  </ComponentDeclarations>
  
  
  <!-- APPLICATION DESCRIPTION -->
  <ApplicationDescription applicationComponent="instanceRemoteCharacterEmbodiment3DSpark" applicationConfig="/GeneralEca.ini">
    <!-- Paso 1/2: Instantiate components -->
    <ComponentInstances>

	  <Instance instanceName="instanceRemoteCharacterEmbodiment3DSpark" componentID ="idRemoteCharacterEmbodiment3DSpark" configuration="/ComponentConfigurations/CharacterEmbodiment3DSpark.ini"/>
	  
	   <Instance instanceName="instanceEyeContactSpark" componentID ="idEyeContactSpark" configuration="/ComponentConfigurations/EyeContactSpark.ini"/>
	  
	  <Instance instanceName="instanceUpdater1" componentID ="idUpdater1"/>
	  
	  <Instance instanceName="instanceRemoteLoquendoVoiceSpark" componentID ="idRemoteLoquendoVoiceSpark"/>

	  <Instance instanceName="instanceVoiceStartSpark" componentID ="idVoiceStartSpark" configuration="/ComponentConfigurations/VoiceStartSpark.ini"/>
	  	  
    </ComponentInstances>
    
    <!-- Paso 2/2: Connect interfaces -->
    <InterfaceConnections>
	  
	  <Connect interface="IEyes" providedBy="instanceRemoteCharacterEmbodiment3DSpark" requiredBy="instanceEyeContactSpark" />
	  <Connect interface="INeck" providedBy="instanceRemoteCharacterEmbodiment3DSpark" requiredBy="instanceEyeContactSpark" />
	  <Connect interface="IAudioQueue" providedBy="instanceRemoteLoquendoVoiceSpark" requiredBy="instanceRemoteCharacterEmbodiment3DSpark" />
	  

		<Connect interface="IControlVoice" providedBy="instanceVoiceStartSpark" requiredBy="instanceRemoteCharacterEmbodiment3DSpark" />
	  
	  <Connect interface="IUpdateable2" providedBy="instanceVoiceStartSpark" requiredBy="instanceUpdater1" />
	  <Connect interface="IUpdateable1" providedBy="instanceEyeContactSpark" requiredBy="instanceUpdater1" />
	  <Connect interface="IUpdateable" providedBy="instanceUpdater1" requiredBy="instanceRemoteCharacterEmbodiment3DSpark" />


	 <Connect interface="IFaceExpression" providedBy="instanceRemoteCharacterEmbodiment3DSpark" 		     requiredBy="instanceVoiceStartSpark" />

	<Connect interface="IVoice" providedBy="instanceRemoteLoquendoVoiceSpark" requiredBy="instanceVoiceStartSpark" />
	  
	
  
      <ConnectAll interface="IAsyncFatalErrorHandler" providedBy="instanceRemoteCharacterEmbodiment3DSpark"/>
    </InterfaceConnections>
  </ApplicationDescription>
</ComponentNetwork>

=== adele-robots/fiona/SPARKS/Run/xml/testAll.xml
<?xml version="1.0" encoding="utf-8"?>
<ComponentNetwork xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ComponentNetwork.xsd">

    <!-- COMPONENT DECLARATION -->
  <ComponentDeclarations>
    <Component  id="idRemoteCharacterEmbodiment3DComponent"  type="RemoteCharacterEmbodiment3DComponent" plugin="libRemoteCharacterEmbodiment3DSpark.so">
      <ProvidedInterfaces>
        <Interface name="IFaceExpression" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="IEyes" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="INeck" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="IAnimation" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IConcurrent" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IAsyncFatalErrorHandler" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IApplication" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IEventQueue" />
      </ProvidedInterfaces>
	  <RequiredInterfaces>
        <Interface name="IUpdateable" />
		<Interface name="IAudioQueue" />
		<Interface name="IAsyncFatalErrorHandler" />
		<Interface name="IVoice" />
      </RequiredInterfaces>
    </Component>

    <Component id="idRemoteLoquendoVoiceComponent"  type="RemoteLoquendoVoiceComponent" plugin="libRemoteLoquendoVoiceSpark.so">
      <ProvidedInterfaces>
	<Interface name="IAudioQueue" />
	<Interface name="IVoice" />
      </ProvidedInterfaces>
    </Component>

	
    <Component id="idEyeContactComponent"  type="EyeContactComponent" plugin="libEyeContactSpark.so">
      <ProvidedInterfaces>
        <Interface name="IDetectedFacePositionConsumer" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IUpdateable1" />
      </ProvidedInterfaces>
      <RequiredInterfaces>
        <Interface name="INeck" />
        <Interface name="IEyes" />
      </RequiredInterfaces>
    </Component>
	
     <Component id="idUpdater1"  type="Updater1" plugin="libUpdaterSpark.so">
      <ProvidedInterfaces>
        <Interface name="IUpdateable" />
      </ProvidedInterfaces>
	    <RequiredInterfaces>
        <Interface name="IUpdateable1" />
      </RequiredInterfaces>
    </Component>
	
     <Component id="idAVInputComponent"  type="AVInputComponent" plugin="libAVInputSpark.so">
      <ProvidedInterfaces>
        <Interface name="IConcurrent" />
      </ProvidedInterfaces>
	
      <RequiredInterfaces>
        <Interface name="IAsyncFatalErrorHandler" />
	<Interface name="IAudioConsumer" />
	<Interface name="IVideoConsumer" />
      </RequiredInterfaces>
    </Component>

    <Component id="idFaceTrackerThreadComponent"  type="FaceTrackerThreadComponent" plugin="libFaceTrackerThreadComponent.so">
      <ProvidedInterfaces>
        <Interface name="IVideoConsumer" />
	<Interface name="IConcurrent" />
      </ProvidedInterfaces>
	
      <RequiredInterfaces>
        <Interface name="IDetectedFacePositionConsumer" />
	<Interface name="IAsyncFatalErrorHandler" />
      </RequiredInterfaces>
    </Component>

	 <Component id="idAudioConsumerComponent"  type="AudioConsumerComponent" plugin="libAudioConsumerComponent.so">
      <ProvidedInterfaces>
        <Interface name="IAudioConsumer" />
      </ProvidedInterfaces>
	
      <RequiredInterfaces>
      </RequiredInterfaces>
    </Component>

	
  </ComponentDeclarations>
  
  
  <!-- APPLICATION DESCRIPTION -->
  <ApplicationDescription applicationComponent="instanceRemoteCharacterEmbodiment3DComponent" applicationConfig="/Eca.ini">
    <!-- Paso 1/2: Instantiate components -->
    <ComponentInstances>

	  <Instance instanceName="instanceAudioConsumerComponent" componentID ="idAudioConsumerComponent"/>

	  <Instance instanceName="instanceAVInputComponent" componentID ="idAVInputComponent"/>

	  <Instance instanceName="instanceFaceTrackerThreadComponent" componentID ="idFaceTrackerThreadComponent"/>
      
	  <Instance instanceName="instanceRemoteCharacterEmbodiment3DComponent" componentID ="idRemoteCharacterEmbodiment3DComponent"/>
	  
	  <Instance instanceName="instanceEyeContactComponent" componentID ="idEyeContactComponent"/>
	  
	  <Instance instanceName="instanceUpdater1" componentID ="idUpdater1"/>
	  
	  <Instance instanceName="instanceRemoteLoquendoVoiceComponent" componentID ="idRemoteLoquendoVoiceComponent"/>
	  

		
	  	  
    </ComponentInstances>
    
    <!-- Paso 2/2: Connect interfaces -->
    <InterfaceConnections>
	  
	  
	  <Connect interface="IEyes" providedBy="instanceRemoteCharacterEmbodiment3DComponent" requiredBy="instanceEyeContactComponent" />
	  <Connect interface="INeck" providedBy="instanceRemoteCharacterEmbodiment3DComponent" requiredBy="instanceEyeContactComponent" />
	  <Connect interface="IAudioQueue" providedBy="instanceRemoteLoquendoVoiceComponent" requiredBy="instanceRemoteCharacterEmbodiment3DComponent" />
	  <Connect interface="IVoice" providedBy="instanceRemoteLoquendoVoiceComponent" requiredBy="instanceRemoteCharacterEmbodiment3DComponent" />


	  <Connect interface="IVoice" providedBy="instanceRemoteLoquendoVoiceComponent" requiredBy="instanceTestRemoteRendererComponent" />
	  
	  <Connect interface="IUpdateable1" providedBy="instanceEyeContactComponent" requiredBy="instanceUpdater1" />
	  <Connect interface="IUpdateable" providedBy="instanceUpdater1" requiredBy="instanceRemoteCharacterEmbodiment3DComponent" />

	  <Connect interface="IVideoConsumer" providedBy="instanceFaceTrackerThreadComponent" requiredBy="instanceAVInputComponent" />
	  <Connect interface="IAudioConsumer" providedBy="instanceAudioConsumerComponent" requiredBy="instanceAVInputComponent" />
<Connect interface="IDetectedFacePositionConsumer" providedBy="instanceEyeContactComponent" requiredBy="instanceFaceTrackerThreadComponent" />
	
	  
      <ConnectAll interface="IAsyncFatalErrorHandler" providedBy="instanceRemoteCharacterEmbodiment3DComponent"/>
    </InterfaceConnections>
  </ApplicationDescription>
</ComponentNetwork>
