=== adele-robots/fiona/SPARKS/ApplicationDataDevelopment/Plugins/ComponentNetwork.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="ComponentNetwork" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
  <xs:element name="Interface">
    <xs:complexType>
      <xs:attribute name="name" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="ComponentNetwork" msdata:IsDataSet="true" msdata:Locale="en-US">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="Interface" />
        <xs:element name="ComponentDeclarations">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Component" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="ProvidedInterfaces" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element ref="Interface" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="RequiredInterfaces" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element ref="Interface" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Parameters" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Parameter" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="name" type="xs:string" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string" />
                  <xs:attribute name="type" type="xs:string" />
                  <xs:attribute name="plugin" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="ApplicationDescription">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ComponentInstances" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Instance" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="ParameterValues" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="assing" minOccurs="0" maxOccurs="unbounded">
                                  <xs:complexType>
                                    <xs:attribute name="parameter" type="xs:string" />
                                    <xs:attribute name="value" type="xs:string" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="instanceName" type="xs:string" />
                        <xs:attribute name="componentID" type="xs:string" />
                        <xs:attribute name="config" type="xs:string" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="InterfaceConnections" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Connect" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="interface" type="xs:string" />
                        <xs:attribute name="providedBy" type="xs:string" />
                        <xs:attribute name="requiredBy" type="xs:string" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== adele-robots/fiona/FIONEG/ext/datos/nfs/configpresets/base/avatar.xml
<?xml version="1.0" encoding="utf-8"?>
<ComponentNetwork xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ComponentNetwork.xsd">

<!-- COMPONENT DECLARATION -->
<ComponentDeclarations>
<Component id="idBlankSpark"  type="BlankSpark" plugin="libBlankSpark.so">
<ProvidedInterfaces>
</ProvidedInterfaces>
<RequiredInterfaces>
</RequiredInterfaces>
</Component>

<Component  id="idRemoteCharacterEmbodiment3DSpark"  type="RemoteCharacterEmbodiment3DSpark" plugin="libRemoteCharacterEmbodiment3DSpark.so">
<ProvidedInterfaces>
<Interface name="ICamera" />
<Interface name="IAnimation" />
<Interface name="IEyes" />
<Interface name="IConcurrent" />
<Interface name="IFrameEventPublisher" />
<Interface name="IFaceExpression" />
<Interface name="IApplication" />
<Interface name="INeck" />
<Interface name="IEventQueue" />
<Interface name="IAsyncFatalErrorHandler" />
</ProvidedInterfaces>
<RequiredInterfaces>
<Interface name="IControlVoice" />
<Interface name="IAsyncFatalErrorHandler" />
<Interface name="IAudioQueue" />
</RequiredInterfaces>
</Component>

<Component  id="idVoiceStartSpark"  type="VoiceStartSpark" plugin="libVoiceStartSpark.so">
<ProvidedInterfaces>
<Interface name="IControlVoice" />
</ProvidedInterfaces>
<RequiredInterfaces>
<Interface name="IFlow&lt;char*&gt;" />
<Interface name="IFaceExpression" />
<Interface name="IFrameEventPublisher" />
</RequiredInterfaces>
</Component>

<Component  id="idCameraControlSpark"  type="CameraControlSpark" plugin="libCameraControlSpark.so">
<ProvidedInterfaces>
</ProvidedInterfaces>
<RequiredInterfaces>
<Interface name="ICamera" />
<Interface name="IFrameEventPublisher" />
</RequiredInterfaces>
</Component>

<Component  id="idFliteVoiceThreadSpark"  type="FliteVoiceThreadSpark" plugin="libFliteVoiceThreadSpark.so">
<ProvidedInterfaces>
<Interface name="IAudioQueue" />
<Interface name="IConcurrent" />
<Interface name="IFlow&lt;char*&gt;" />
</ProvidedInterfaces>
<RequiredInterfaces>
<Interface name="IAsyncFatalErrorHandler" />
</RequiredInterfaces>
</Component>
</ComponentDeclarations>

<!-- APPLICATION DESCRIPTION -->
<ApplicationDescription applicationComponent="instanceRemoteCharacterEmbodiment3DSpark" applicationConfig="/generalConf.ini">
<!-- Paso 1/2: Instantiate components -->

<ComponentInstances>
<Instance instanceName="instanceBlankSpark" componentID ="idBlankSpark"/>
<Instance instanceName="instanceRemoteCharacterEmbodiment3DSpark" componentID ="idRemoteCharacterEmbodiment3DSpark" configuration="/RemoteCharacterEmbodiment3DSpark.ini"/>
<Instance instanceName="instanceVoiceStartSpark" componentID ="idVoiceStartSpark" configuration="/VoiceStartSpark.ini"/>
<Instance instanceName="instanceCameraControlSpark" componentID ="idCameraControlSpark" configuration="/CameraControlSpark.ini"/>
<Instance instanceName="instanceFliteVoiceThreadSpark" componentID ="idFliteVoiceThreadSpark" configuration="/FliteVoiceThreadSpark.ini"/>
</ComponentInstances>

<!-- Paso 2/2: Connect interfaces -->
<InterfaceConnections>
 <Connect interface="IControlVoice" providedBy="instanceVoiceStartSpark" requiredBy="instanceRemoteCharacterEmbodiment3DSpark" />
 <Connect interface="IFaceExpression" providedBy="instanceRemoteCharacterEmbodiment3DSpark" requiredBy="instanceVoiceStartSpark" />
 <Connect interface="IAudioQueue" providedBy="instanceFliteVoiceThreadSpark" requiredBy="instanceRemoteCharacterEmbodiment3DSpark" />
 <Connect interface="IFlow&lt;char*&gt;" providedBy="instanceFliteVoiceThreadSpark" requiredBy="instanceVoiceStartSpark" />
 <Connect interface="ICamera" providedBy="instanceRemoteCharacterEmbodiment3DSpark" requiredBy="instanceCameraControlSpark" />
<ConnectAll interface="IAsyncFatalErrorHandler" providedBy="instanceRemoteCharacterEmbodiment3DSpark"/>
<ConnectAll interface="IFrameEventPublisher" providedBy="instanceRemoteCharacterEmbodiment3DSpark"/>
</InterfaceConnections>
</ApplicationDescription>
</ComponentNetwork>

=== adele-robots/fiona/SPARKS/Run/xml/testVideoConsumer.xml
<?xml version="1.0" encoding="utf-8"?>
<ComponentNetwork xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ComponentNetwork.xsd">

    <!-- COMPONENT DECLARATION -->
  <ComponentDeclarations>
    <Component  id="idRemoteCharacterEmbodiment3DSpark"  type="RemoteCharacterEmbodiment3DSpark" plugin="libRemoteCharacterEmbodiment3DSpark.so">
      <ProvidedInterfaces>
        <Interface name="IFaceExpression" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="IEyes" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="INeck" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="IAnimation" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="ICamera" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IConcurrent" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IAsyncFatalErrorHandler" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IApplication" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IEventQueue" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="IFrameEventPublisher" />
      </ProvidedInterfaces>
      <RequiredInterfaces>
	<Interface name="IAudioQueue" />
	<Interface name="IAsyncFatalErrorHandler" />
	<Interface name="IControlVoice" />
      </RequiredInterfaces>
    </Component>

    <Component id="idRemoteFliteVoiceSpark"  type="RemoteFliteVoiceSpark" plugin="libRemoteFliteVoiceSpark.so">
      <ProvidedInterfaces>
	<Interface name="IVoice" />
	<Interface name="IAudioQueue" />
      </ProvidedInterfaces>
    </Component>

	
    <Component id="idEyeContactSpark"  type="EyeContactSpark" plugin="libEyeContactSpark.so">
      <ProvidedInterfaces>
        <Interface name="IDetectedFacePositionConsumer" />
      </ProvidedInterfaces>
      <RequiredInterfaces>
        <Interface name="INeck" />
        <Interface name="IEyes" />
	<Interface name="IFrameEventPublisher" />
      </RequiredInterfaces>
    </Component>
	

    <Component id="idVoiceStartSpark"  type="VoiceStartSpark" plugin="libVoiceStartSpark.so">
      <ProvidedInterfaces>
	<Interface name="IControlVoice" />	
      </ProvidedInterfaces>
      <RequiredInterfaces>
        <Interface name="IVoice" />
	<Interface name="IFaceExpression" />
	<Interface name="IFrameEventPublisher" />
      </RequiredInterfaces>
    </Component>


     <Component id="idAVInputSpark"  type="AVInputSpark" plugin="libAVInputSpark.so">
      <ProvidedInterfaces>
        <Interface name="IConcurrent" />
      </ProvidedInterfaces>
	
      <RequiredInterfaces>
        <Interface name="IAsyncFatalErrorHandler" />
	<Interface name="IAudioConsumer" />
	<Interface name="IVideoConsumer" />
      </RequiredInterfaces>
    </Component>

 <Component  id="idASRSpark"  type="ASRSpark" plugin="libASRSpark.so">
      <ProvidedInterfaces>
        <Interface name="IAudioConsumer" />
      </ProvidedInterfaces>
      <RequiredInterfaces>
        <Interface name="IVoice" />           
      </RequiredInterfaces>      
    </Component>
    


	 <Component id="idVideoConsumerSpark"  type="VideoConsumerSpark" plugin="libVideoConsumerSpark.so">
      <ProvidedInterfaces>
        <Interface name="IVideoConsumer" />
      </ProvidedInterfaces>
	
      <RequiredInterfaces>
      </RequiredInterfaces>
    </Component>


     <Component id="idCameraControl"  type="CameraControlSpark" plugin="libCameraControlSpark.so">
      <RequiredInterfaces>
        <Interface name="ICamera" />
	<Interface name="IFrameEventPublisher" />
      </RequiredInterfaces>
    </Component>
	
	
  </ComponentDeclarations>
  
  
  <!-- APPLICATION DESCRIPTION -->
  <ApplicationDescription applicationComponent="instanceRemoteCharacterEmbodiment3DSpark" applicationConfig="/GeneralEca.ini">
    <!-- Paso 1/2: Instantiate components -->
    <ComponentInstances>
      <Instance instanceName="instanceVideoConsumerSpark" componentID ="idVideoConsumerSpark"/>
      <Instance instanceName="instanceASRSpark" componentID ="idASRSpark" configuration="/ComponentConfigurations/ASRSpark.ini"/>
	  <Instance instanceName="instanceAVInputSpark" componentID ="idAVInputSpark" configuration="/ComponentConfigurations/AVInputSpark.ini"/>	  
	  <Instance instanceName="instanceRemoteCharacterEmbodiment3DSpark" componentID ="idRemoteCharacterEmbodiment3DSpark" configuration="/ComponentConfigurations/CharacterEmbodiment3DSpark.ini"/>
	  <Instance instanceName="instanceEyeContactSpark" componentID ="idEyeContactSpark" configuration="/ComponentConfigurations/EyeContactSpark.ini"/>
	  <Instance instanceName="instanceRemoteFliteVoiceSpark" componentID ="idRemoteFliteVoiceSpark"/>
	  <Instance instanceName="instanceVoiceStartSpark" componentID ="idVoiceStartSpark" configuration="/ComponentConfigurations/VoiceStartSpark.ini"/>
	  <Instance instanceName="instanceCameraControl" componentID ="idCameraControl" configuration="/ComponentConfigurations/CameraControlSpark.ini"/>
	  	  
    </ComponentInstances>
    
    <!-- Paso 2/2: Connect interfaces -->
    <InterfaceConnections>
	  
	  <Connect interface="IEyes" providedBy="instanceRemoteCharacterEmbodiment3DSpark" requiredBy="instanceEyeContactSpark" />
	  <Connect interface="INeck" providedBy="instanceRemoteCharacterEmbodiment3DSpark" requiredBy="instanceEyeContactSpark" />
	  <Connect interface="IAudioQueue" providedBy="instanceRemoteFliteVoiceSpark" requiredBy="instanceRemoteCharacterEmbodiment3DSpark" />
	  <Connect interface="IControlVoice" providedBy="instanceVoiceStartSpark" requiredBy="instanceRemoteCharacterEmbodiment3DSpark" />
	  <Connect interface="IFaceExpression" providedBy="instanceRemoteCharacterEmbodiment3DSpark" requiredBy="instanceVoiceStartSpark" />
      <Connect interface="IVoice" providedBy="instanceRemoteFliteVoiceSpark" requiredBy="instanceASRSpark" />
      <Connect interface="IVoice" providedBy="instanceRemoteFliteVoiceSpark" requiredBy="instanceVoiceStartSpark" />
	  <Connect interface="ICamera" providedBy="instanceRemoteCharacterEmbodiment3DSpark" requiredBy="instanceCameraControl" />
      <Connect interface="IVideoConsumer" providedBy="instanceVideoConsumerSpark" requiredBy="instanceAVInputSpark" />
	  <Connect interface="IDetectedFacePositionConsumer" providedBy="instanceEyeContactSpark" requiredBy="instanceVideoConsumerSpark" />
	  <Connect interface="IAudioConsumer" providedBy="instanceASRSpark" requiredBy="instanceAVInputSpark" />
	   
      <ConnectAll interface="IAsyncFatalErrorHandler" providedBy="instanceRemoteCharacterEmbodiment3DSpark"/>
      <ConnectAll interface="IFrameEventPublisher" providedBy="instanceRemoteCharacterEmbodiment3DSpark"/>
     
    </InterfaceConnections>
  </ApplicationDescription>
</ComponentNetwork>

=== adele-robots/fiona/SPARKS/TestRebecca/testRebeccaWithInterfaces.xml
<?xml version="1.0" encoding="utf-8"?>
<ComponentNetwork xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ComponentNetwork.xsd">

    <!-- COMPONENT DECLARATION -->
  <ComponentDeclarations>


   <Component  id="idRebeccaAIMLSpark"  type="RebeccaAIMLSpark" plugin="libRebeccaAIMLSpark.so">
      <ProvidedInterfaces>
        <Interface name="IVoice" />
      </ProvidedInterfaces>
      <RequiredInterfaces>
        <Interface name="IVoice" />
      </RequiredInterfaces>
    </Component>

   <Component  id="idTestRebecca"  type="TestRebecca" plugin="libTestRebecca.so">
      <ProvidedInterfaces>
        <Interface name="IVoice" />
      </ProvidedInterfaces>
      <RequiredInterfaces>
        <Interface name="IVoice" />
      </RequiredInterfaces>
    </Component>
  
  </ComponentDeclarations>
  
  
  <!-- APPLICATION DESCRIPTION -->
  <ApplicationDescription applicationComponent="instanceTestRebecca" applicationConfig="/Eca.ini">
    <!-- Paso 1/2: Instantiate components -->
    <ComponentInstances>

      <Instance instanceName="instanceTestRebecca" componentID ="idTestRebecca" >
      </Instance>
      <Instance instanceName="instanceRebeccaAIMLSpark" componentID ="idRebeccaAIMLSpark" configuration="/ComponentConfigurations/RebeccaAIMLSpark.ini" >
      </Instance>          
       
    </ComponentInstances>
    
    <!-- Paso 2/2: Connect interfaces -->
    <InterfaceConnections>
      <Connect interface="IVoice" providedBy="instanceTestRebecca" requiredBy="instanceRebeccaAIMLSpark" />
      <Connect interface="IVoice" providedBy="instanceRebeccaAIMLSpark" requiredBy="instanceTestRebecca" />
    </InterfaceConnections>
  </ApplicationDescription>
</ComponentNetwork>

=== adele-robots/fiona/SPARKS/TestChatSpark/testChatSparkWithRebecca.xml
<?xml version="1.0" encoding="utf-8"?>
<ComponentNetwork xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ComponentNetwork.xsd">

    <!-- COMPONENT DECLARATION -->
  <ComponentDeclarations>

	<Component  id="idChatThreadSpark"  type="ChatThreadSpark" plugin="libChatThreadSpark.so">
      <ProvidedInterfaces>
        <Interface name="IVoice" />
        <Interface name="IConcurrent" />
      </ProvidedInterfaces>
      <RequiredInterfaces>
        <Interface name="IVoice" />  
        <Interface name="IAsyncFatalErrorHandler" />      
      </RequiredInterfaces>
    </Component>

   <Component  id="idRebeccaAIMLSpark"  type="RebeccaAIMLSpark" plugin="libRebeccaAIMLSpark.so">
      <ProvidedInterfaces>
        <Interface name="IVoice" />
      </ProvidedInterfaces>
      <RequiredInterfaces>
        <Interface name="IVoice" />
      </RequiredInterfaces>
    </Component>

   <Component  id="idTestChatSpark"  type="TestChatSpark" plugin="libTestChatSpark.so">
     <ProvidedInterfaces>
        <Interface name="IApplication" />        
		<Interface name="IAsyncFatalErrorHandler" />
      </ProvidedInterfaces>
   </Component>
  
  </ComponentDeclarations>
  
  
  <!-- APPLICATION DESCRIPTION -->
  <ApplicationDescription applicationComponent="instanceTestChatSpark" applicationConfig="/Eca.ini">
    <!-- Paso 1/2: Instantiate components -->
    <ComponentInstances>
	  
	  <Instance instanceName="instanceChatThreadSpark" componentID ="idChatThreadSpark">
      </Instance>
      <Instance instanceName="instanceRebeccaAIMLSpark" componentID ="idRebeccaAIMLSpark" configuration="/ComponentConfigurations/RebeccaAIMLSpark.ini" >
      </Instance>
      <Instance instanceName="instanceTestChatSpark" componentID ="idTestChatSpark" >
      </Instance>      
       
    </ComponentInstances>
    
    <!-- Paso 2/2: Connect interfaces -->
    <InterfaceConnections>
      <Connect interface="IVoice" providedBy="instanceChatThreadSpark" requiredBy="instanceRebeccaAIMLSpark" />
      <Connect interface="IVoice" providedBy="instanceRebeccaAIMLSpark" requiredBy="instanceChatThreadSpark" />
      <ConnectAll interface="IAsyncFatalErrorHandler" providedBy="instanceTestChatSpark"/>
    </InterfaceConnections>
  </ApplicationDescription>
</ComponentNetwork>

=== adele-robots/fiona/SPARKS/Run/xml/testASRSpark.xml
<?xml version="1.0" encoding="utf-8"?>
<ComponentNetwork xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ComponentNetwork.xsd">

    <!-- COMPONENT DECLARATION -->
  <ComponentDeclarations>	

   <Component  id="idASRSpark"  type="ASRSpark" plugin="libASRSpark.so">
      <ProvidedInterfaces>
        <Interface name="IAudioConsumer" />
      </ProvidedInterfaces>
      <RequiredInterfaces>
        <Interface name="IVoice" />           
      </RequiredInterfaces>
      
    </Component>
    
    <Component  id="idChatThreadSpark"  type="ChatThreadSpark" plugin="libChatThreadSpark.so">
      <ProvidedInterfaces>
        <Interface name="IVoice" />
        <Interface name="IConcurrent" />
      </ProvidedInterfaces>
      <RequiredInterfaces>
        <Interface name="IVoice" />  
        <Interface name="IAsyncFatalErrorHandler" />      
      </RequiredInterfaces>
    </Component>
    
    <Component  id="idRebeccaAIMLSpark"  type="RebeccaAIMLSpark" plugin="libRebeccaAIMLSpark.so">
      <ProvidedInterfaces>
        <Interface name="IVoice" />
      </ProvidedInterfaces>
      <RequiredInterfaces>
        <Interface name="IVoice" />
      </RequiredInterfaces>
    </Component>

   <Component  id="idTestASRSpark"  type="TestASRSpark" plugin="libTestASRSpark.so">
     <ProvidedInterfaces>
        <Interface name="IApplication" />        
		<Interface name="IAsyncFatalErrorHandler" />
      </ProvidedInterfaces>
      <RequiredInterfaces>
        <Interface name="IAudioConsumer" />
      </RequiredInterfaces>
   </Component>
  
  </ComponentDeclarations>
  
  
  <!-- APPLICATION DESCRIPTION -->
  <ApplicationDescription applicationComponent="instanceTestASRSpark" applicationConfig="/Eca.ini">
    <!-- Paso 1/2: Instantiate components -->
    <ComponentInstances>	  
	  
      <Instance instanceName="instanceASRSpark" componentID ="idASRSpark" configuration="/ComponentConfigurations/ASRSpark.ini" >
      </Instance>
      <Instance instanceName="instanceChatThreadSpark" componentID ="idChatThreadSpark">
      </Instance>
      <Instance instanceName="instanceRebeccaAIMLSpark" componentID ="idRebeccaAIMLSpark" configuration="/ComponentConfigurations/RebeccaAIMLSpark.ini" >
      </Instance>
      <Instance instanceName="instanceTestASRSpark" componentID ="idTestASRSpark" configuration="/ComponentConfigurations/ASRSpark.ini">
      </Instance>      
       
    </ComponentInstances>
    
    <!-- Paso 2/2: Connect interfaces -->
    <InterfaceConnections>      
      <Connect interface="IAudioConsumer" providedBy="instanceASRSpark" requiredBy="instanceTestASRSpark" />      
      <Connect interface="IVoice" providedBy="instanceTestASRSpark" requiredBy="instanceChatThreadSpark" />
      <Connect interface="IVoice" providedBy="instanceChatThreadSpark" requiredBy="instanceRebeccaAIMLSpark" />
      <Connect interface="IVoice" providedBy="instanceRebeccaAIMLSpark" requiredBy="instanceASRSpark" />
      <ConnectAll interface="IAsyncFatalErrorHandler" providedBy="instanceTestASRSpark"/>
    </InterfaceConnections>
  </ApplicationDescription>
</ComponentNetwork>

=== adele-robots/fiona/SPARKS/Run/xml/testFlite.xml
<?xml version="1.0" encoding="utf-8"?>
<ComponentNetwork xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ComponentNetwork.xsd">

    <!-- COMPONENT DECLARATION -->
  <ComponentDeclarations>
    <Component  id="idRemoteCharacterEmbodiment3DSpark"  type="RemoteCharacterEmbodiment3DSpark" plugin="libRemoteCharacterEmbodiment3DSpark.so">
      <ProvidedInterfaces>
<!-- Testing if it is not necessary to declare the provided and required interfaces of each Spark, except IConcurrent and interfaces
			named in <ConnectAll> -->

<!--        <Interface name="IFaceExpression" />
        <Interface name="IEyes" />
        <Interface name="INeck" />
        <Interface name="IAnimation" />
        <Interface name="ICamera" />
        <Interface name="IAsyncFatalErrorHandler" />
        <Interface name="IApplication" />
        <Interface name="IEventQueue" />
-->
        <Interface name="IFrameEventPublisher" />

        <Interface name="IConcurrent" />
      </ProvidedInterfaces>
      <RequiredInterfaces>
<!--        <Interface name="IAudioQueue" />
        <Interface name="IControlVoice" />
-->
        <Interface name="IAsyncFatalErrorHandler" />
      </RequiredInterfaces>
    </Component>

    <Component id="idFliteVoiceThreadSpark"  type="FliteVoiceThreadSpark" plugin="libFliteVoiceThreadSpark.so">
      <ProvidedInterfaces>
<!--    <Interface name="IFlow&lt;char*>" />
        <Interface name="IAudioQueue" />  
-->
        <Interface name="IConcurrent" />
      </ProvidedInterfaces>
      <RequiredInterfaces>
        <Interface name="IAsyncFatalErrorHandler" />
      </RequiredInterfaces>
    </Component>

<Component id="idVoiceStartSpark"  type="VoiceStartSpark" plugin="libVoiceStartSpark.so">
      <ProvidedInterfaces>
	<!--			<Interface name="IControlVoice" />	 -->
      </ProvidedInterfaces>
      <RequiredInterfaces>
 <!--       <Interface name="IFlow&lt;char*>" />
        <Interface name="IFaceExpression" />
-->
        <Interface name="IFrameEventPublisher" />

      </RequiredInterfaces>
    </Component>	



  </ComponentDeclarations>
  
  
  <!-- APPLICATION DESCRIPTION -->
  <ApplicationDescription applicationComponent="instanceRemoteCharacterEmbodiment3DSpark" applicationConfig="/GeneralEca.ini">
    <!-- Paso 1/2: Instantiate components -->
    <ComponentInstances> 
	  <Instance instanceName="instanceRemoteCharacterEmbodiment3DSpark" componentID ="idRemoteCharacterEmbodiment3DSpark" configuration="/ComponentConfigurations/CharacterEmbodiment3DSpark.ini"/>
	  <Instance instanceName="instanceFliteVoiceThreadSpark" componentID ="idFliteVoiceThreadSpark" configuration="/ComponentConfigurations/FliteVoiceSpark.ini"/>
	  <Instance instanceName="instanceVoiceStartSpark" componentID ="idVoiceStartSpark" configuration="/ComponentConfigurations/VoiceStartSpark.ini"/>	
	</ComponentInstances>
    
    <!-- Paso 2/2: Connect interfaces -->
    <InterfaceConnections>
	  <Connect interface="IAudioQueue" providedBy="instanceFliteVoiceThreadSpark" requiredBy="instanceRemoteCharacterEmbodiment3DSpark" />	  
	  <Connect interface="IControlVoice" providedBy="instanceVoiceStartSpark" requiredBy="instanceRemoteCharacterEmbodiment3DSpark" />
	  <Connect interface="IFaceExpression" providedBy="instanceRemoteCharacterEmbodiment3DSpark" requiredBy="instanceVoiceStartSpark" />
	  <Connect interface="IFlow&lt;char*>" providedBy="instanceFliteVoiceThreadSpark" requiredBy="instanceVoiceStartSpark" />
      <ConnectAll interface="IAsyncFatalErrorHandler" providedBy="instanceRemoteCharacterEmbodiment3DSpark"/>
      <ConnectAll interface="IFrameEventPublisher" providedBy="instanceRemoteCharacterEmbodiment3DSpark"/>
    </InterfaceConnections>
  </ApplicationDescription>
</ComponentNetwork>
