=== adele-robots/fiona/SPARKS/ApplicationDataDevelopment/Plugins/ComponentNetwork.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="ComponentNetwork" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
  <xs:element name="Interface">
    <xs:complexType>
      <xs:attribute name="name" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="ComponentNetwork" msdata:IsDataSet="true" msdata:Locale="en-US">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="Interface" />
        <xs:element name="ComponentDeclarations">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Component" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="ProvidedInterfaces" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element ref="Interface" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="RequiredInterfaces" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element ref="Interface" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Parameters" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Parameter" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="name" type="xs:string" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string" />
                  <xs:attribute name="type" type="xs:string" />
                  <xs:attribute name="plugin" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="ApplicationDescription">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ComponentInstances" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Instance" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="ParameterValues" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="assing" minOccurs="0" maxOccurs="unbounded">
                                  <xs:complexType>
                                    <xs:attribute name="parameter" type="xs:string" />
                                    <xs:attribute name="value" type="xs:string" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="instanceName" type="xs:string" />
                        <xs:attribute name="componentID" type="xs:string" />
                        <xs:attribute name="config" type="xs:string" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="InterfaceConnections" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Connect" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="interface" type="xs:string" />
                        <xs:attribute name="providedBy" type="xs:string" />
                        <xs:attribute name="requiredBy" type="xs:string" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== adele-robots/fiona/SPARKS/Run/xml/testFaceTrackerComponent.xml
<?xml version="1.0" encoding="utf-8"?>
<ComponentNetwork xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ComponentNetwork.xsd">

  <!-- COMPONENT DECLARATION -->
  <ComponentDeclarations>

     <Component id="idAVInputSpark"  type="AVInputSpark" plugin="libAVInputSpark.so">
      <ProvidedInterfaces>
        <Interface name="IConcurrent" />
        
      </ProvidedInterfaces>
      
      <RequiredInterfaces>
        <Interface name="IAsyncFatalErrorHandler" />
 	<Interface name="IVideoConsumer" /> 
	<Interface name="IAudioConsumer" />

      </RequiredInterfaces>
    </Component>

    
    <Component id="idFaceTrackerComponent"  type="FaceTrackerSpark" plugin="libFaceTrackerSpark.so">
      <ProvidedInterfaces>
        <Interface name="IVideoConsumer" />
        <Interface name="IThreadProc" />
      </ProvidedInterfaces>
      
	    <RequiredInterfaces>
        <Interface name="IDetectedFacePositionConsumer" />
      </RequiredInterfaces>
    </Component>
	
	 <Component id="idThreadComponent"  type="ThreadComponent" plugin="libThreadSpark.so">
      <ProvidedInterfaces>
        <Interface name="IConcurrent" />
      </ProvidedInterfaces>
	  
      <RequiredInterfaces>
        <Interface name="IThreadProc" />
		    <Interface name="IAsyncFatalErrorHandler" />
      </RequiredInterfaces>
    </Component>
	
	  <Component id="idTestFaceTrackerComponent"  type="TestFaceTrackerSpark" plugin="libTestFaceTrackerSpark.so">
      <ProvidedInterfaces>
        <Interface name="IApplication" />
        <Interface name="IThreadProc" />
		    <Interface name="IAsyncFatalErrorHandler" />
      </ProvidedInterfaces>
    </Component>

	
	 <Component id="idAudioConsumerSpark"  type="AudioConsumerSpark" plugin="libAudioConsumerSpark.so">
      <ProvidedInterfaces>
        <Interface name="IAudioConsumer" />
      </ProvidedInterfaces>
	
      <RequiredInterfaces>
      </RequiredInterfaces>
    </Component>

	   <Component id="idFaceTrackerThreadSpark"  type="FaceTrackerThreadSpark" plugin="libFaceTrackerThreadSpark.so">
      <ProvidedInterfaces>
        <Interface name="IVideoConsumer" />
	<Interface name="IConcurrent" />
      </ProvidedInterfaces>
	
      <RequiredInterfaces>
        <Interface name="IDetectedFacePositionConsumer" />
	<Interface name="IAsyncFatalErrorHandler" />
      </RequiredInterfaces>
    </Component>


  </ComponentDeclarations>
  
  
  <!-- APPLICATION DESCRIPTION -->
  <ApplicationDescription applicationComponent="instanceTestFaceTrackerComponent" applicationConfig="/Eca.ini">
    <!-- Paso 1/2: Instantiate components -->
    <ComponentInstances>
     
	<Instance instanceName="instanceAudioConsumerSpark" componentID ="idAudioConsumerSpark"/>
      <Instance instanceName="instanceAVInputSpark" componentID ="idAVInputSpark" config="/path/to/specific/file.ini">
         </Instance>
      <Instance instanceName="instanceFaceTrackerThreadSpark" componentID ="idFaceTrackerThreadSpark" config="/path/to/specific/file.ini">
         </Instance>
      <Instance instanceName="instanceTestFaceTrackerComponent" componentID ="idTestFaceTrackerComponent"/>
  
  	
    </ComponentInstances>
    <!-- Paso 2/2: Connect interfaces -->
    <InterfaceConnections>
       <Connect interface="IDetectedFacePositionConsumer" providedBy="instanceTestFaceTrackerComponent" requiredBy="instanceFaceTrackerThreadSpark" />
       <Connect interface="IVideoConsumer" providedBy="instanceFaceTrackerThreadSpark" requiredBy="instanceAVInputSpark" />
	<Connect interface="IAudioConsumer" providedBy="instanceAudioConsumerSpark" requiredBy="instanceAVInputSpark" />

      <ConnectAll interface="IAsyncFatalErrorHandler" providedBy="instanceTestFaceTrackerComponent"/>
    </InterfaceConnections>
  </ApplicationDescription>
</ComponentNetwork>

=== adele-robots/fiona/SPARKS/Run/xml/testRCE3D.xml
<?xml version="1.0" encoding="utf-8"?>
<ComponentNetwork xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ComponentNetwork.xsd">

    <!-- COMPONENT DECLARATION -->
  <ComponentDeclarations>
    <Component  id="idRemoteCharacterEmbodiment3DComponent"  type="RemoteCharacterEmbodiment3DSpark" plugin="libRemoteCharacterEmbodiment3DSpark.so">
      <ProvidedInterfaces>
        <Interface name="IFaceExpression" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="IEyes" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="INeck" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="IAnimation" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IConcurrent" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IAsyncFatalErrorHandler" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IApplication" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IEventQueue" />
      </ProvidedInterfaces>
	  <RequiredInterfaces>
        <Interface name="IUpdateable" />
		<Interface name="IAudioQueue" />
		<Interface name="IAsyncFatalErrorHandler" />
      </RequiredInterfaces>
    </Component>

    <Component id="idRemoteLoquendoVoiceComponent"  type="RemoteFliteVoiceSpark" plugin="libRemoteFliteVoiceSpark.so">
      <ProvidedInterfaces>
	<Interface name="IAudioQueue" />
      </ProvidedInterfaces>
    </Component>

	
    <Component id="idEyeContactComponent"  type="EyeContactSpark" plugin="libEyeContactSpark.so">
      <ProvidedInterfaces>
        <Interface name="IDetectedFacePositionConsumer" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IUpdateable1" />
      </ProvidedInterfaces>
      <RequiredInterfaces>
        <Interface name="INeck" />
        <Interface name="IEyes" />
      </RequiredInterfaces>
    </Component>
	
     <Component id="idUpdater1"  type="Updater1" plugin="libUpdaterSpark.so">
      <ProvidedInterfaces>
        <Interface name="IUpdateable" />
      </ProvidedInterfaces>
	    <RequiredInterfaces>
        <Interface name="IUpdateable1" />
      </RequiredInterfaces>
    </Component>
	
	
  </ComponentDeclarations>
  
  
  <!-- APPLICATION DESCRIPTION -->
  <ApplicationDescription applicationComponent="instanceRemoteCharacterEmbodiment3DComponent" applicationConfig="/Eca.ini">
    <!-- Paso 1/2: Instantiate components -->
    <ComponentInstances>
      
	  <Instance instanceName="instanceRemoteCharacterEmbodiment3DComponent" componentID ="idRemoteCharacterEmbodiment3DComponent"/>
	  
	  <Instance instanceName="instanceEyeContactComponent" componentID ="idEyeContactComponent"/>
	  
	  <Instance instanceName="instanceUpdater1" componentID ="idUpdater1"/>
	  
	  <Instance instanceName="instanceRemoteLoquendoVoiceComponent" componentID ="idRemoteLoquendoVoiceComponent"/>
	  	  
    </ComponentInstances>
    
    <!-- Paso 2/2: Connect interfaces -->
    <InterfaceConnections>
	  
	  <Connect interface="IEyes" providedBy="instanceRemoteCharacterEmbodiment3DComponent" requiredBy="instanceEyeContactComponent" />
	  <Connect interface="INeck" providedBy="instanceRemoteCharacterEmbodiment3DComponent" requiredBy="instanceEyeContactComponent" />
	  <Connect interface="IAudioQueue" providedBy="instanceRemoteLoquendoVoiceComponent" requiredBy="instanceRemoteCharacterEmbodiment3DComponent" />
	  

	  <Connect interface="IVoice" providedBy="instanceRemoteLoquendoVoiceComponent" requiredBy="instanceTestRemoteRendererComponent" />
	  
	  <Connect interface="IUpdateable1" providedBy="instanceEyeContactComponent" requiredBy="instanceUpdater1" />
	  <Connect interface="IUpdateable" providedBy="instanceUpdater1" requiredBy="instanceRemoteCharacterEmbodiment3DComponent" />
	  
	  
      <ConnectAll interface="IAsyncFatalErrorHandler" providedBy="instanceRemoteCharacterEmbodiment3DComponent"/>
    </InterfaceConnections>
  </ApplicationDescription>
</ComponentNetwork>

=== adele-robots/fiona/FIONEG/ext/datos/nfs/users/private/1cf79a1b295a9393d63a76f528a3ed90/avatar.xml
<?xml version="1.0" encoding="utf-8"?>
<ComponentNetwork xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ComponentNetwork.xsd">

<!-- COMPONENT DECLARATION -->
<ComponentDeclarations>
<Component  id="idRemoteCharacterEmbodiment3DSpark"  type="RemoteCharacterEmbodiment3DSpark" plugin="libRemoteCharacterEmbodiment3DSpark.so">
<ProvidedInterfaces>
<Interface name="ICamera" />
<Interface name="IAnimation" />
<Interface name="IEyes" />
<Interface name="IConcurrent" />
<Interface name="IFrameEventPublisher" />
<Interface name="IFaceExpression" />
<Interface name="IApplication" />
<Interface name="IEventQueue" />
<Interface name="INeck" />
<Interface name="IAsyncFatalErrorHandler" />
</ProvidedInterfaces>
<RequiredInterfaces>
<Interface name="IControlVoice" />
<Interface name="IAsyncFatalErrorHandler" />
<Interface name="IAudioQueue" />
</RequiredInterfaces>
</Component>

<Component  id="idEyeContactSpark"  type="EyeContactSpark" plugin="libEyeContactSpark.so">
<ProvidedInterfaces>
<Interface name="IDetectedFacePositionConsumer" />
</ProvidedInterfaces>
<RequiredInterfaces>
<Interface name="IFrameEventPublisher" />
<Interface name="INeck" />
<Interface name="IEyes" />
</RequiredInterfaces>
</Component>

<Component  id="idRemoteFliteVoiceSpark"  type="RemoteFliteVoiceSpark" plugin="libRemoteFliteVoiceSpark.so">
<ProvidedInterfaces>
<Interface name="IVoice" />
<Interface name="IAudioQueue" />
</ProvidedInterfaces>
<RequiredInterfaces>
</RequiredInterfaces>
</Component>

<Component  id="idVoiceStartSpark"  type="VoiceStartSpark" plugin="libVoiceStartSpark.so">
<ProvidedInterfaces>
<Interface name="IControlVoice" />
</ProvidedInterfaces>
<RequiredInterfaces>
<Interface name="IVoice" />
<Interface name="IFaceExpression" />
<Interface name="IFrameEventPublisher" />
</RequiredInterfaces>
</Component>

<Component  id="idCameraControlSpark"  type="CameraControlSpark" plugin="libCameraControlSpark.so">
<ProvidedInterfaces>
</ProvidedInterfaces>
<RequiredInterfaces>
<Interface name="ICamera" />
<Interface name="IFrameEventPublisher" />
</RequiredInterfaces>
</Component>
</ComponentDeclarations>

<!-- APPLICATION DESCRIPTION -->
<ApplicationDescription applicationComponent="instanceRemoteCharacterEmbodiment3DSpark" applicationConfig="/generalConf.ini">
<!-- Paso 1/2: Instantiate components -->

<ComponentInstances>
<Instance instanceName="instanceRemoteCharacterEmbodiment3DSpark" componentID ="idRemoteCharacterEmbodiment3DSpark" configuration="/RemoteCharacterEmbodiment3DSpark.ini"/>
<Instance instanceName="instanceEyeContactSpark" componentID ="idEyeContactSpark" configuration="/EyeContactSpark.ini"/>
<Instance instanceName="instanceRemoteFliteVoiceSpark" componentID ="idRemoteFliteVoiceSpark" configuration="/RemoteFliteVoiceSpark.ini"/>
<Instance instanceName="instanceVoiceStartSpark" componentID ="idVoiceStartSpark" configuration="/VoiceStartSpark.ini"/>
<Instance instanceName="instanceCameraControlSpark" componentID ="idCameraControlSpark" configuration="/CameraControlSpark.ini"/>
</ComponentInstances>

<!-- Paso 2/2: Connect interfaces -->
<InterfaceConnections>
 <Connect interface="INeck" providedBy="instanceRemoteCharacterEmbodiment3DSpark" requiredBy="instanceEyeContactSpark" />
 <Connect interface="IEyes" providedBy="instanceRemoteCharacterEmbodiment3DSpark" requiredBy="instanceEyeContactSpark" />
 <Connect interface="ICamera" providedBy="instanceRemoteCharacterEmbodiment3DSpark" requiredBy="instanceCameraControlSpark" />
 <Connect interface="IVoice" providedBy="instanceRemoteFliteVoiceSpark" requiredBy="instanceVoiceStartSpark" />
 <Connect interface="IControlVoice" providedBy="instanceVoiceStartSpark" requiredBy="instanceRemoteCharacterEmbodiment3DSpark" />
 <Connect interface="IAudioQueue" providedBy="instanceRemoteFliteVoiceSpark" requiredBy="instanceRemoteCharacterEmbodiment3DSpark" />
 <Connect interface="IFaceExpression" providedBy="instanceRemoteCharacterEmbodiment3DSpark" requiredBy="instanceVoiceStartSpark" />
<ConnectAll interface="IAsyncFatalErrorHandler" providedBy="instanceRemoteCharacterEmbodiment3DSpark"/>
<ConnectAll interface="IFrameEventPublisher" providedBy="instanceRemoteCharacterEmbodiment3DSpark"/>
</InterfaceConnections>
</ApplicationDescription>
</ComponentNetwork>

=== adele-robots/fiona/SPARKS/Run/xml/testScene3DComponent.xml
<?xml version="1.0" encoding="utf-8"?>
<ComponentNetwork xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ComponentNetwork.xsd">

    <!-- COMPONENT DECLARATION -->
  <ComponentDeclarations>


   <Component  id="idScene3DComponent"  type="Scene3DComponent" plugin="libScene3DSpark.so">
      <ProvidedInterfaces>
        <Interface name="IFaceExpression" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="IEyes" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="INeck" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="IAnimation" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="IRenderizable" />
      </ProvidedInterfaces>
    </Component>


    <Component id="idTestScene3DComponent"  type="TestScene3DComponent" plugin="libTestScene3DSpark.so">
      <ProvidedInterfaces>
        <Interface name="IApplication" />
      </ProvidedInterfaces>
      <RequiredInterfaces>
        <Interface name="IRenderizable" />
      </RequiredInterfaces>
     </Component>

  </ComponentDeclarations>
  
  
  <!-- APPLICATION DESCRIPTION -->
  <ApplicationDescription applicationComponent="instanceTestScene3D" applicationConfig="/GeneralEca.ini">
    <!-- Paso 1/2: Instantiate components -->
    <ComponentInstances>
      
      <Instance instanceName="instanceTestScene3D" componentID ="idTestScene3DComponent" configuration="/ComponentConfigurations/CharacterEmbodiment3DSpark.ini">
      </Instance>
      
      <Instance instanceName="instanceScene3D" componentID ="idScene3DComponent" configuration="/ComponentConfigurations/CharacterEmbodiment3DSpark.ini">
      </Instance>
      
	    
       
    </ComponentInstances>
    
    <!-- Paso 2/2: Connect interfaces -->
    <InterfaceConnections>
      <Connect interface="IRenderizable" providedBy="instanceScene3D" requiredBy="instanceTestScene3D" />
    </InterfaceConnections>
  </ApplicationDescription>
</ComponentNetwork>

=== adele-robots/fiona/SPARKS/Run/avatar.xml
<?xml version="1.0" encoding="utf-8"?>
<ComponentNetwork xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ComponentNetwork.xsd">

    <!-- COMPONENT DECLARATION -->
  <ComponentDeclarations>
    <Component  id="idRemoteCharacterEmbodiment3DSpark"  type="RemoteCharacterEmbodiment3DSpark" plugin="libRemoteCharacterEmbodiment3DSpark.so">
      <ProvidedInterfaces>
        <Interface name="IFaceExpression" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="IEyes" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="INeck" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="IAnimation" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IConcurrent" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IAsyncFatalErrorHandler" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IApplication" />
      </ProvidedInterfaces>
	  <ProvidedInterfaces>
        <Interface name="IEventQueue" />
      </ProvidedInterfaces>
      <ProvidedInterfaces>
        <Interface name="IFrameEventPublisher" />
      </ProvidedInterfaces>
      <RequiredInterfaces>
	<Interface name="IAudioQueue" />
	<Interface name="IAsyncFatalErrorHandler" />
	<Interface name="IControlVoice" />
      </RequiredInterfaces>
    </Component>

    <Component id="idRemoteFliteVoiceSpark"  type="RemoteFliteVoiceSpark" plugin="libRemoteFliteVoiceSpark.so">
      <ProvidedInterfaces>
	<Interface name="IVoice" />
	<Interface name="IAudioQueue" />
      </ProvidedInterfaces>
    </Component>

	
    <Component id="idEyeContactSpark"  type="EyeContactSpark" plugin="libEyeContactSpark.so">
      <ProvidedInterfaces>
        <Interface name="IDetectedFacePositionConsumer" />
      </ProvidedInterfaces>
      <RequiredInterfaces>
        <Interface name="INeck" />
        <Interface name="IEyes" />
	<Interface name="IFrameEventPublisher" />
      </RequiredInterfaces>
    </Component>
	

    <Component id="idVoiceStartSpark"  type="VoiceStartSpark" plugin="libVoiceStartSpark.so">
      <ProvidedInterfaces>
	<Interface name="IControlVoice" />	
      </ProvidedInterfaces>
      <RequiredInterfaces>
        <Interface name="IVoice" />
	<Interface name="IFaceExpression" />
	<Interface name="IFrameEventPublisher" />
      </RequiredInterfaces>
    </Component>


     <Component id="idAVInputSpark"  type="AVInputSpark" plugin="libAVInputSpark.so">
      <ProvidedInterfaces>
        <Interface name="IConcurrent" />
      </ProvidedInterfaces>
	
      <RequiredInterfaces>
        <Interface name="IAsyncFatalErrorHandler" />
	<Interface name="IAudioConsumer" />
	<Interface name="IVideoConsumer" />
      </RequiredInterfaces>
    </Component>

    <Component id="idFaceTrackerSpark"  type="FaceTrackerThreadSpark" plugin="libFaceTrackerSpark.so">
      <ProvidedInterfaces>
        <Interface name="IVideoConsumer" />
	<Interface name="IConcurrent" />
      </ProvidedInterfaces>
	
      <RequiredInterfaces>
        <Interface name="IDetectedFacePositionConsumer" />
	<Interface name="IAsyncFatalErrorHandler" />
      </RequiredInterfaces>
    </Component>

	 <Component id="idAudioConsumerSpark"  type="AudioConsumerSpark" plugin="libAudioConsumerSpark.so">
      <ProvidedInterfaces>
        <Interface name="IAudioConsumer" />
      </ProvidedInterfaces>
	
      <RequiredInterfaces>
      </RequiredInterfaces>
    </Component>


     <Component id="idCameraControl"  type="CameraControlSpark" plugin="libCameraControlSpark.so">
      <RequiredInterfaces>
        <Interface name="ICamera" />
	<Interface name="IFrameEventPublisher" />
      </RequiredInterfaces>
    </Component>
	
	
  </ComponentDeclarations>
  
  
  <!-- APPLICATION DESCRIPTION -->
  <ApplicationDescription applicationComponent="instanceRemoteCharacterEmbodiment3DSpark" applicationConfig="/generalConf.ini">
    <!-- Paso 1/2: Instantiate components -->
    <ComponentInstances>
      
	  <Instance instanceName="instanceAudioConsumerSpark" componentID ="idAudioConsumerSpark"/>

	  <Instance instanceName="instanceAVInputSpark" componentID ="idAVInputSpark" configuration="/AVInputSpark.ini"/>

	  <Instance instanceName="instanceFaceTrackerSpark" componentID ="idFaceTrackerSpark" configuration="/FaceTrackerSpark.ini"/>
	  <Instance instanceName="instanceRemoteCharacterEmbodiment3DSpark" componentID ="idRemoteCharacterEmbodiment3DSpark" configuration="/RemoteCharacterEmbodiment3DSpark.ini"/>
	  
	   <Instance instanceName="instanceEyeContactSpark" componentID ="idEyeContactSpark" configuration="/EyeContactSpark.ini"/>
	  
	  <Instance instanceName="instanceRemoteFliteVoiceSpark" componentID ="idRemoteFliteVoiceSpark"/>

	  <Instance instanceName="instanceVoiceStartSpark" componentID ="idVoiceStartSpark" configuration="/VoiceStartSpark.ini"/>
	  <Instance instanceName="instanceCameraControl" componentID ="idCameraControl" configuration="/CameraControlSpark.ini"/>
	  	  
    </ComponentInstances>
    
    <!-- Paso 2/2: Connect interfaces -->
    <InterfaceConnections>
	  
	  <Connect interface="IEyes" providedBy="instanceRemoteCharacterEmbodiment3DSpark" requiredBy="instanceEyeContactSpark" />
	  <Connect interface="INeck" providedBy="instanceRemoteCharacterEmbodiment3DSpark" requiredBy="instanceEyeContactSpark" />
	  <Connect interface="IAudioQueue" providedBy="instanceRemoteFliteVoiceSpark" requiredBy="instanceRemoteCharacterEmbodiment3DSpark" />
	  

		<Connect interface="IControlVoice" providedBy="instanceVoiceStartSpark" requiredBy="instanceRemoteCharacterEmbodiment3DSpark" />


	 <Connect interface="IFaceExpression" providedBy="instanceRemoteCharacterEmbodiment3DSpark" 		     requiredBy="instanceVoiceStartSpark" />

	<Connect interface="IVoice" providedBy="instanceRemoteFliteVoiceSpark" requiredBy="instanceVoiceStartSpark" />
	<Connect interface="ICamera" providedBy="instanceRemoteCharacterEmbodiment3DSpark" requiredBy="instanceCameraControl" />
	  

	<Connect interface="IVideoConsumer" providedBy="instanceFaceTrackerSpark" requiredBy="instanceAVInputSpark" />
	  <Connect interface="IAudioConsumer" providedBy="instanceAudioConsumerSpark" requiredBy="instanceAVInputSpark" />
	<Connect interface="IDetectedFacePositionConsumer" providedBy="instanceEyeContactSpark" requiredBy="instanceFaceTrackerSpark" />
	
  
      <ConnectAll interface="IAsyncFatalErrorHandler" providedBy="instanceRemoteCharacterEmbodiment3DSpark"/>
      <ConnectAll interface="IFrameEventPublisher" providedBy="instanceRemoteCharacterEmbodiment3DSpark"/>
    </InterfaceConnections>
  </ApplicationDescription>
</ComponentNetwork>
